// PNT1 additive proof (decisions.md, "Adding engine fields and CSS longhands"): adding the PNT1 paint longhands may change existing
// outputs only by adding those longhands. Compares the working tree with a base commit and exits 1 on any other difference.
// Adapted from GRID G0's check-grid-additive.ts (origin/master), with the new longhands taken from the PNT1 families.
// Run: node --conditions=dragon-internal packages/dragon/test/tools/check-pnt1-additive.ts <base-commit>
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { LONGHANDS } from '../../src/css/properties.ts';

const base = process.argv[2];
if (base === undefined) throw new Error('usage: check-pnt1-additive.ts <base-commit>');
const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
const git = (...args: string[]): string => execFileSync('git', args, { cwd: root, encoding: 'utf8', maxBuffer: 1 << 30 });
/**
 * The longhands added since the base, in LONGHANDS order (the order captures and emitted rules list them in): those the base's
 * captures do not record (read from one base capture, since the base's compiler is not importable here). PNT1 adds its families
 * branch by branch, so the set depends on the base.
 */
const probe = git('ls-tree', '-r', '--name-only', base, '--', 'packages/parity/expected').split('\n').find((p) => p.endsWith('.web.json'));
if (probe === undefined) throw new Error(`base ${base} has no capture to read its longhands from`);
const baseKeys = new Set(Object.keys(((JSON.parse(git('show', `${base}:${probe}`)) as { nodes: { computed: Record<string, string> | null }[] }).nodes.find((n) => n.computed !== null)?.computed) ?? {}));
if (baseKeys.size === 0) throw new Error(`base capture ${probe} has no computed record`);
const NEW: readonly string[] = LONGHANDS.filter((p) => !baseKeys.has(p));
console.log(`longhands added since ${base}: ${NEW.join(', ')}`);
const NEW_SET = new Set(NEW);

const CAPTURES = /^packages\/parity\/(expected|expected-dpr)\/.*\.json$/;
const EMITTED = /^packages\/parity\/emitted\/.*\.css$/;
const UA = /^packages\/dragon\/src\/ua\/.*\.generated\.ts$/;
/** Outputs that must stay byte-identical: layout and break vectors, Chrome line breaks and pixel references. */
const FROZEN = /^packages\/(layout\/vectors|layout\/break-vectors|parity\/expected-breaks|parity\/expected-pixels)\//;
/** The pixel manifest lists every case, so it may gain entries for the new cases only. */
const MANIFEST = /^packages\/parity\/expected-pixels\/[^/]+\/manifest\.json$/;

const problems: string[] = [];
const counts = { captures: 0, emitted: 0, ua: 0, other: 0, added: 0 };
const others: string[] = [];

type Node = { readonly computed?: { readonly [k: string]: string } | null };
type Capture = { readonly nodes: readonly Node[] };

/** A capture must gain exactly the new longhands on every computed record and be byte-identical once they are removed. */
function checkCapture(path: string, before: string, after: string): void {
  const b = JSON.parse(before) as Capture;
  const a = JSON.parse(after) as Capture;
  if (JSON.stringify(b, null, 2) + '\n' !== before || JSON.stringify(a, null, 2) + '\n' !== after) problems.push(`${path}: not in the capture writer's format`);
  if (a.nodes.length !== b.nodes.length) {
    problems.push(`${path}: ${b.nodes.length} nodes became ${a.nodes.length}`);
    return;
  }
  let records = 0;
  const stripped = {
    ...a,
    nodes: a.nodes.map((n, i) => {
      const was = b.nodes[i] as Node;
      if (n.computed === null || n.computed === undefined) return n;
      records++;
      const added = Object.keys(n.computed).filter((k) => !(was.computed !== null && was.computed !== undefined && k in was.computed));
      if (added.length !== NEW.length || added.some((k, j) => k !== NEW[j])) problems.push(`${path}: node ${i} added [${added.join(', ')}], expected the PNT1 longhands in order`);
      return { ...n, computed: Object.fromEntries(Object.entries(n.computed).filter(([k]) => !NEW_SET.has(k))) };
    }),
  };
  if (records === 0) problems.push(`${path}: changed with no computed record`);
  if (JSON.stringify(stripped, null, 2) + '\n' !== before) problems.push(`${path}: differs from the base beyond the added PNT1 longhands`);
}

const HEADER = /^\/\* Generated by Dragon from compilation [0-9a-f]+\. Do not edit\. \*\/$/;
const newDeclaration = (line: string): string | null => {
  const m = /^ {2}([a-z-]+): [^;]*;$/.exec(line);
  return m !== null && NEW_SET.has(m[1] as string) ? (m[1] as string) : null;
};

/** Emitted CSS: the header may name a new compilation; every rule gains exactly the new declarations, in order, and nothing else. */
function checkEmitted(path: string, before: string, after: string): void {
  const b = before.split('\n');
  const a = after.split('\n');
  if (!HEADER.test(b[0] as string) || !HEADER.test(a[0] as string)) problems.push(`${path}: header is not a compilation header`);
  const kept = a.slice(1).filter((l) => newDeclaration(l) === null);
  if (kept.join('\n') !== b.slice(1).join('\n')) problems.push(`${path}: differs from the base beyond added PNT1 declarations`);
  let rule: string[] | null = null;
  let rules = 0;
  for (const l of a.slice(1)) {
    if (l.endsWith(' {')) rule = [];
    else if (l === '}' && rule !== null) {
      rules++;
      if (rule.join(' ') !== NEW.join(' ')) problems.push(`${path}: a rule added [${rule.join(', ')}]`);
      rule = null;
    } else if (rule !== null) {
      const d = newDeclaration(l);
      if (d !== null) rule.push(d);
      else if (rule.length > 0) problems.push(`${path}: ${l.trim()} follows an added PNT1 declaration`);
    }
  }
  if (rules === 0) problems.push(`${path}: changed with no rule`);
}

/** The UA tables: lines may only be added, and each added line is one new longhand's captured value. */
function checkUa(path: string, before: string, after: string): void {
  const added = /^\s*"([a-z-]+)": "[^"]*",?$/;
  const kept = after.split('\n').filter((l) => {
    const m = added.exec(l);
    return m === null || !NEW_SET.has(m[1] as string);
  });
  if (kept.join('\n') !== before) problems.push(`${path}: differs from the base beyond added PNT1 longhand lines`);
}

/** The manifest with the entries of cases the base does not list removed, per case list. */
function baseCasesOnly(after: unknown, before: unknown): unknown {
  if (Array.isArray(after) && Array.isArray(before)) {
    const known = new Set(before.map((e) => (typeof e === 'object' && e !== null ? (e as { case?: unknown }).case : undefined)));
    return after.filter((e) => typeof e !== 'object' || e === null || !('case' in e) || known.has((e as { case: unknown }).case)).map((e, i) => baseCasesOnly(e, before[i]));
  }
  if (typeof after === 'object' && after !== null && typeof before === 'object' && before !== null) {
    return Object.fromEntries(Object.entries(after).map(([k, v]) => [k, baseCasesOnly(v, (before as { [k: string]: unknown })[k])]));
  }
  return after;
}

function checkManifest(path: string, before: string, after: string): void {
  if (JSON.stringify(baseCasesOnly(JSON.parse(after), JSON.parse(before))) !== JSON.stringify(JSON.parse(before))) problems.push(`${path}: differs from the base beyond entries for new cases`);
}

const changed = git('diff', '--name-status', '--no-renames', base).split('\n').filter((l) => l !== '');
const modified = new Set<string>();
for (const line of changed) {
  const [status, path] = line.split('\t') as [string, string];
  if (status === 'A') {
    counts.added++;
    continue;
  }
  if (status !== 'M') {
    if (CAPTURES.test(path) || EMITTED.test(path) || UA.test(path) || FROZEN.test(path)) problems.push(`${path}: status ${status}`);
    else others.push(`${status} ${path}`);
    continue;
  }
  modified.add(path);
  const before = git('show', `${base}:${path}`);
  const after = readFileSync(join(root, path), 'utf8');
  if (MANIFEST.test(path)) checkManifest(path, before, after);
  else if (FROZEN.test(path)) problems.push(`${path}: must be byte-identical`);
  else if (CAPTURES.test(path)) {
    counts.captures++;
    checkCapture(path, before, after);
  } else if (EMITTED.test(path)) {
    counts.emitted++;
    checkEmitted(path, before, after);
  } else if (UA.test(path)) {
    counts.ua++;
    checkUa(path, before, after);
  } else {
    counts.other++;
    others.push(`M ${path}`);
  }
}

// Every base capture with a computed record and every base emitted file must have gained the new longhands: none may be stale.
const baseFiles = git('ls-tree', '-r', '--name-only', base, '--', 'packages/parity/expected', 'packages/parity/expected-dpr', 'packages/parity/emitted').split('\n').filter((p) => CAPTURES.test(p) || EMITTED.test(p));
for (const p of baseFiles) {
  if (modified.has(p)) continue;
  const text = git('show', `${base}:${p}`);
  if (EMITTED.test(p) ? text.includes(' {\n') : text.includes('"computed": {')) problems.push(`${p}: unchanged, so it lacks the PNT1 longhands`);
}

console.log(`base ${base}: ${counts.captures} captures, ${counts.emitted} emitted CSS files and ${counts.ua} UA tables checked; ${counts.added} files added`);
console.log(`other changed files (${others.length}):\n${others.map((o) => `  ${o}`).join('\n')}`);
if (problems.length > 0) {
  console.log(`FAIL: ${problems.length} problems\n${problems.slice(0, 50).join('\n')}`);
  process.exit(1);
}
console.log('PASS: every capture, emitted file and UA table differs from the base only by the added PNT1 longhands; the pixel manifest only gains new cases; vectors, break vectors, Chrome breaks and pixels are byte-identical');
