// formatDiagnostic (docs/api.md §6.1): one human-readable rendering of the shared diagnostic object, located through the
// report's revisioned source registry. Offsets are UTF-16 code units; lines and columns are 1-based.
import type { Diagnostic, Fix, Origin, SourceFile, Span } from '../types.ts';

function position(span: Span, sources: readonly SourceFile[]): string {
  const src = sources.find((s) => s.ref.uri === span.source.uri);
  if (src === undefined) return `${span.source.uri}@${span.start}`;
  let line = 1;
  let lineStart = 0;
  const end = Math.min(span.start, src.text.length);
  for (let i = 0; i < end; i++) {
    if (src.text.charCodeAt(i) === 10) {
      line++;
      lineStart = i + 1;
    }
  }
  const stale = src.ref.revision !== span.source.revision || src.ref.hash !== span.source.hash ? ' (stale revision)' : '';
  return `${src.displayPath}:${line}:${span.start - lineStart + 1}${stale}`;
}

function where(origin: Origin, sources: readonly SourceFile[]): string {
  switch (origin.kind) {
    case 'authored':
      return position(origin.span, sources);
    case 'inherited':
      return `${where(origin.from, sources)} (inherited by ${origin.element})`;
    case 'builtin':
      return `<${origin.dataset}: ${origin.entry}>`;
    case 'generated':
      return origin.causes.length === 0 ? `<generated by ${origin.pass}>` : `${where(origin.causes[0] as Origin, sources)} (generated by ${origin.pass})`;
    case 'unlocated':
      return `<unlocated: ${origin.reason}>`;
  }
}

function fixText(fix: Fix): string {
  if ('manual' in fix) return `${fix.title}: ${fix.manual}`;
  return `${fix.title} (${fix.edits.length} guarded edit${fix.edits.length === 1 ? '' : 's'})`;
}

export function formatDiagnostic(diagnostic: Diagnostic, sources: readonly SourceFile[]): string {
  const target = diagnostic.target === null ? '' : ` [${diagnostic.target}]`;
  const lines = [`${where(diagnostic.origin, sources)}: ${diagnostic.severity} ${diagnostic.code}${target}: ${diagnostic.message}`, `  why: ${diagnostic.why}`];
  for (const r of diagnostic.related) lines.push(`  related: ${where(r.origin, sources)}: ${r.message}`);
  if (diagnostic.fix !== null) lines.push(`  fix: ${fixText(diagnostic.fix)}`);
  return lines.join('\n');
}
