// S2: configuration, input, CSS and lowering.
import { diagnosticFeature, edit, error, manual } from '../entry.ts';

export const S2 = diagnosticFeature(
  [
    'DRAGON_CONFIG_INVALID',
    'DRAGON_INPUT_INVALID',
    'DRAGON_PRODUCER_ERROR',
    'DRAGON_INCOMPLETE_INPUT',
    'DRAGON_SOURCE_HASH_MISMATCH',
    'DRAGON_SPAN_INVALID',
    'DRAGON_TREE_SCHEMA',
    'DRAGON_TREE_UNSUPPORTED',
    'DRAGON_CSS_PARSE',
    'DRAGON_CSS_INVALID_VALUE',
    'DRAGON_UNSUPPORTED_AT_RULE',
    'DRAGON_UNSUPPORTED_SELECTOR',
    'DRAGON_UNSUPPORTED_IMPORTANT',
    'DRAGON_UNSUPPORTED_PROPERTY',
    'DRAGON_UNSUPPORTED_VALUE',
    'DRAGON_UNSUPPORTED_ELEMENT',
    'DRAGON_UNSUPPORTED_ATTRIBUTE',
    'DRAGON_UNSUPPORTED_FONT',
    'DRAGON_LOWERING_FAILED',
  ],
  {
    DRAGON_CONFIG_INVALID: error('The project configuration is invalid.', 'Targets and project identity must be known before anything compiles.', manual('Fix the configuration', 'Configure { ios: { minimum: "15.0" } } and/or { web: {} } with a non-empty projectId.')),
    DRAGON_INPUT_INVALID: error('The front-end result is malformed.', 'Compile consumes a complete FrontEndResult; missing or extra fields could hide front-end errors.', manual('Supply a complete FrontEndResult', 'Match docs/api.md §2.1 exactly.')),
    DRAGON_PRODUCER_ERROR: error('The front end reported an error.', 'Errors recovered by the producer block every output that depends on its analysis.', manual('Fix the producer error', 'Fix the source the producer rejected, then compile again.')),
    DRAGON_INCOMPLETE_INPUT: error('The input is not a closed application.', 'Only a closed application with an element tree can produce application outputs.', manual('Supply a closed application', 'Pass completeness "closed-application" with a tree.')),
    DRAGON_SOURCE_HASH_MISMATCH: error('A source hash does not match its text.', 'Spans and fixes are only valid against the exact source text they were computed from.', manual('Recompute the hash', 'Hash the exact UTF-8 text with SHA-256 and pass "sha256:<hex>".')),
    DRAGON_SPAN_INVALID: error('A span points outside its source.', 'Every authored origin must resolve to text in the snapshot, in UTF-16 offsets.', manual('Fix the span', 'Point the span at a source in the snapshot, with 0 <= start <= end <= length and the same revision and hash.')),
    DRAGON_TREE_SCHEMA: error('The tree schema or revision is not supported.', 'Draft @0 inputs require an exact revision match (docs/api.md §9).', manual('Emit the supported schema', 'Emit schema "dragon/tree@0" with the compiler\'s TREE_SCHEMA_REVISION.')),
    DRAGON_TREE_UNSUPPORTED: error('The tree uses a structure milestone 1 does not compile.', 'Milestone 1 compiles one document entry whose document element is <html>.', manual('Restructure the tree', 'Compile one document per project, rooted at <html> with <body>.')),
    DRAGON_CSS_PARSE: error('The CSS does not parse.', 'A recovered CSS parse error would silently drop declarations.', manual('Fix the CSS syntax', 'Fix the CSS at this location.')),
    DRAGON_CSS_INVALID_VALUE: error('The value does not match the property grammar.', 'Browsers drop invalid declarations; native output would disagree about which declaration wins.', manual('Use a valid value', 'Use a value that matches the @webref/css grammar for this property.')),
    DRAGON_UNSUPPORTED_AT_RULE: error('This at-rule is not supported.', 'Milestone 1 resolves only plain style rules; an at-rule would change which rules apply.', manual('Move the rules out of the at-rule', 'Move the declarations you want to keep into plain top-level style rules, then remove the at-rule. Deleting the at-rule alone would also delete the rules inside it.')),
    DRAGON_UNSUPPORTED_SELECTOR: error('This selector is not supported.', 'Selectors compile only when their match can be proven on the fixed element tree at build time; pseudo-elements and interaction states are not built yet.', manual('Rewrite the selector', 'Use type, class, [ui-*] attribute and structural pseudo-class selectors, joined by descendant, child or sibling combinators.')),
    DRAGON_UNSUPPORTED_IMPORTANT: error('!important is not supported.', 'Order and specificity decide the cascade in milestone 1.', edit('Remove !important')),
    DRAGON_UNSUPPORTED_PROPERTY: error('This property is not supported.', 'The compiler resolves only the milestone-1 longhands and their shorthands.', edit('Remove the declaration')),
    DRAGON_UNSUPPORTED_VALUE: error('This value is not supported on a configured target.', 'The target\'s support profile has no passing proof for this value.', manual('Use a supported value', 'Use a value the target profile supports.'), 'Milestone 1 refuses this value where its computed result or placement needs layout the engine does not model, so Dragon never guesses what Chrome would do.'),
    DRAGON_UNSUPPORTED_ELEMENT: error('This element is not supported.', 'Dragon resolves only the elements whose Chrome browser defaults it captured, and only where those defaults apply unchanged.', manual('Use a supported element', 'Use a div or another supported element; the message lists them.')),
    DRAGON_UNSUPPORTED_ATTRIBUTE: error('This attribute is not supported.', 'Only ui-* attributes take part in selector matching; other attributes could style elements invisibly.', manual('Use a ui-* attribute or a class', 'Move styling into the stylesheet and select with classes or ui-* attributes.')),
    DRAGON_UNSUPPORTED_FONT: error('This font is not supported by the layout lane.', 'The milestone-1 layout lane measures text only with Ahem.', manual('Use Ahem', 'Set font-family: Ahem on text for the milestone-1 layout lane.')),
    DRAGON_LOWERING_FAILED: error('The ios lowering has no mapping for this value.', 'Every layout field must be set explicitly; there are no engine defaults.', manual('Use a value with a layout mapping', 'Use a value the ios lowering maps.')),
  },
);
