// Chrome 145's legacy display keywords in the compiler (css/display-legacy.ts); packages/parity/test/display-parse.test.ts pins
// the grammar against Chrome itself.
import { describe, expect, it } from 'vitest';
import type { Compiled, FrontEndResult } from '../src/index.ts';
import { createProjectWith, NO_FAULTS, WEB_CSS_PATH } from '../src/internal.ts';
import { div, expectCatalogued, inputFor, spanTextOf } from './helpers.ts';

const FONT = 'body { margin: 0; font-family: Ahem; font-size: 10px; }';
type K = 'ios' | 'android' | 'web';
const compile = (css: string): { input: FrontEndResult; c: Compiled<K> } => {
  const input = inputFor(`${FONT} ${css}`, (r) => [div(r, 'a', ['a'])]);
  return { input, c: createProjectWith({ projectId: 'test', targets: { ios: { minimum: '15.0' }, android: { minSdk: 31 }, web: {} } }, { faults: NO_FAULTS, profiles: 'enforce', direction: 'ltr' }).compile(input) };
};
/** The emitted web CSS without its compilation-digest header, which hashes the authored source. */
const webCss = (c: Compiled<K>): string => {
  const out = c.outputs.web;
  if (out.kind !== 'ready') throw new Error(`web is ${out.kind}: ${c.diagnostics.map((d) => `${d.code} ${d.message}`).join('; ')}`);
  return (out.files.find((f) => f.path === WEB_CSS_PATH) as { text: string }).text.replace(/^\/\* Generated by Dragon from compilation [0-9a-f]+\. Do not edit\. \*\/\n/, '');
};

describe('display: -webkit-box and -webkit-inline-box', () => {
  for (const [value, fix] of [['-webkit-box', 'display: flex'], ['-webkit-inline-box', 'display: inline-flex']] as const) {
    it(`${value} is refused on every target with the legacy box reason, not called invalid`, () => {
      const { input, c } = compile(`.a { display: ${value.toUpperCase()}; }`);
      expect(c.diagnostics.map((d) => [d.code, d.target, d.message])).toEqual([[
        'DRAGON_UNSUPPORTED_VALUE', null,
        `display: ${value} is unsupported: it selects Chrome's legacy -webkit-box layout, which Dragon does not lay out, line clamping with -webkit-box-orient: vertical and -webkit-line-clamp included`,
      ]]);
      expect(spanTextOf(input, c.diagnostics[0] as (typeof c.diagnostics)[number])).toBe(value.toUpperCase());
      expect(c.diagnostics[0]?.fix).toMatchObject({ manual: `Use ${fix}, with flex-direction and the flex properties.` });
      expect([c.outputs.ios.kind, c.outputs.android.kind, c.outputs.web.kind]).toEqual(['blocked', 'blocked', 'blocked']);
      expectCatalogued(c.diagnostics);
    });
  }
  it('the line-clamp pattern is refused for its display and -webkit-line-clamp, and -webkit-box-orient alone is inert (legacy-box.test.ts)', () => {
    const { c } = compile('.a { display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; overflow: hidden; }');
    expect(c.diagnostics.map((d) => [d.code, d.message.split(' ')[0]])).toEqual([['DRAGON_UNSUPPORTED_VALUE', 'display:'], ['DRAGON_UNSUPPORTED_PROPERTY', '-webkit-line-clamp']]);
  });
  it('a var() that substitutes -webkit-box is refused with the same reason', () => {
    const { c } = compile('.a { --d: -webkit-box; display: var(--d); }');
    expect(c.diagnostics.map((d) => [d.code, d.message])).toEqual([['DRAGON_UNSUPPORTED_VALUE', expect.stringMatching(/substitutes to "-webkit-box": display: -webkit-box is unsupported: it selects Chrome's legacy -webkit-box layout/)]]);
  });
});

describe('display: -webkit-flex and -webkit-inline-flex', () => {
  it('compile as flex and inline-flex, as Chrome computes them', () => {
    const plain = compile('.a { display: flex; width: 10px; }').c;
    const prefixed = compile('.a { display: -webkit-flex; width: 10px; }').c;
    expect(prefixed.diagnostics).toEqual([]);
    expect(webCss(prefixed)).toContain('display: flex;');
    expect(webCss(prefixed)).toBe(webCss(plain));
    // inline-flex is unproven in block context, so the two compile to the same refusals.
    const summary = (c: Compiled<K>): string[] => c.diagnostics.map((d) => `${d.code} ${String(d.target)} ${d.message}`);
    const inline = compile('.a { display: inline-flex; width: 10px; }').c;
    expect(summary(inline).length).toBeGreaterThan(0);
    expect(summary(compile('.a { display: -WEBKIT-INLINE-FLEX; width: 10px; }').c)).toEqual(summary(inline));
  });
  it('the autoprefixer chain ends in its last value', () => {
    const { c } = compile('.a { display: -webkit-flex; display: flex; width: 10px; }');
    expect(c.diagnostics).toEqual([]);
  });
});

describe('display values Chrome 145 drops are invalid', () => {
  for (const value of ['run-in', 'grid-lanes', 'inline-grid-lanes', 'ruby-base', 'ruby-base-container', 'ruby-text-container', 'run-in flow', '-webkit-box inline']) {
    it(value, () => {
      expect(compile(`.a { display: ${value}; }`).c.diagnostics.map((d) => [d.code, d.message])).toEqual([['DRAGON_CSS_INVALID_VALUE', `"${value}" is not a valid value for display (@webref/css grammar)`]]);
    });
  }
});
