// P3 (notes/T009-p2b-review-p3-plan.md items 8 and 9): one native layout projection shared by every native target, and the
// android support profile, which holds the iOS row keys and proofs, its statuses derived from the android device lanes (P6a).
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { androidProfile, COMMITTED_PROFILES, createProjectWith, iosLayoutProjection, iosProfile, nativeLayoutProjection, NO_FAULTS, webProfile } from '../src/internal.ts';
import { div, inputFor, text } from './helpers.ts';

const src = join(dirname(fileURLToPath(import.meta.url)), '..', 'src');
const CSS = 'body { margin: 0; font-family: Ahem; font-size: 10px; } .a { width: 50%; padding: 3px; border: 1px solid; } .b { display: flex; gap: 2px; }';
const ENV = { viewport: { width: 400, height: 300 }, devicePixelRatio: 1, rootFont: 'ua-default' } as const;

describe('android support profile', () => {
  const key = (r: { feature: string; context: string }): string => `${r.feature}@${r.context}`;
  it('has exactly the iOS feature@context keys, in the same order', () => {
    expect(androidProfile.target).toBe('android');
    expect(androidProfile.revision).toBe(iosProfile.revision);
    expect(androidProfile.rows.map(key)).toEqual(iosProfile.rows.map(key));
    expect(new Set(androidProfile.rows.map(key)).size).toBe(androidProfile.rows.length);
  });
  it('has the iOS row proofs, and every row is exact or caveat by the android device lanes (P6a promotion rule)', () => {
    expect(androidProfile.rows.length).toBeGreaterThan(0);
    expect(androidProfile.rows.map((r) => r.proofs)).toEqual(iosProfile.rows.map((r) => r.proofs));
    expect(androidProfile.rows.filter((r) => r.status !== 'exact' && r.status !== 'caveat')).toEqual([]);
  });
  it('is a configured target with androidProfile: COMMITTED_PROFILES holds web, ios and android, and android.ts is generated', () => {
    expect(Object.keys(COMMITTED_PROFILES).sort()).toEqual(['android', 'ios', 'web']);
    expect(COMMITTED_PROFILES.ios).toBe(iosProfile);
    expect(COMMITTED_PROFILES.web).toBe(webProfile);
    expect(COMMITTED_PROFILES.android).toBe(androidProfile);
    expect(readFileSync(join(src, 'project.ts'), 'utf8')).toContain("const KNOWN_TARGETS = ['web', 'ios', 'android'] as const;");
    expect(readFileSync(join(src, 'profiles', 'android.ts'), 'utf8')).toMatch(/^\/\/ Generated by scripts\/gen-profile-rows\.ts/);
  });
});

describe('one native layout projection', () => {
  const project = (direction: 'ltr' | 'rtl') => createProjectWith({ projectId: 'test', targets: { ios: { minimum: '15.0' }, web: {} } }, { faults: NO_FAULTS, profiles: 'derive', direction });
  const input = inputFor(CSS, (r) => [div(r, 'a', ['a'], [text(r, 't', 'AB CD')]), div(r, 'b', ['b'], [div(r, 'c', []), div(r, 'd', [])])]);
  it('iosLayoutProjection delegates to nativeLayoutProjection: equal ready results in both directions and at every ratio', () => {
    for (const direction of ['ltr', 'rtl'] as const) {
      const c = project(direction).compile(input);
      for (const devicePixelRatio of [1, 2, 3, 2.625]) {
        const env = { ...ENV, direction, devicePixelRatio };
        const n = nativeLayoutProjection(c, env, []);
        expect(n.kind).toBe('ready');
        expect(iosLayoutProjection(c, env, [])).toEqual(n);
      }
    }
  });
  it('blocked results are equal too: a direction mismatch and an object that is not a compiled result', () => {
    const c = project('ltr').compile(input);
    const env = { ...ENV, direction: 'rtl' as const };
    expect(nativeLayoutProjection(c, env, []).kind).toBe('blocked');
    expect(iosLayoutProjection(c, env, [])).toEqual(nativeLayoutProjection(c, env, []));
    expect(iosLayoutProjection({}, env, [])).toEqual(nativeLayoutProjection({}, env, []));
  });
  it('the lowered tree has a target-neutral name and iosLayoutProjection has no body of its own', () => {
    const internal = readFileSync(join(src, 'internal.ts'), 'utf8');
    expect(readFileSync(join(src, 'project.ts'), 'utf8')).not.toMatch(/iosLowered/);
    expect(internal).not.toMatch(/iosLowered/);
    expect(internal).toMatch(/export function iosLayoutProjection\([^)]*\): LayoutProjection \{\n {2}return nativeLayoutProjection\(compiled, environment, assignment\);\n\}/);
  });
});
