import type { ProfileRow, SupportProfile } from './types.ts';

// Each exact row names the S1 fixtures that exercise the feature; packages/parity proves every named fixture
// passes in the same run (layout aspect only, Linux lane). Missing rows mean unsupported.
function row(feature: string, fixtures: readonly string[]): ProfileRow {
  return { feature, status: 'exact', proofs: [{ aspect: 'layout', lane: 'linux-dragon-layout', fixtures }] };
}

export const iosProfile: SupportProfile = {
  target: 'ios',
  revision: 'm1-s1',
  rows: [
  row("align-content:center", ["flex-wrap-gap-align-content"]),
  row("align-content:flex-start", ["flex-wrap-gap-align-content"]),
  row("align-content:space-between", ["flex-wrap-gap-align-content"]),
  row("align-items:center", ["flex-align-items-stretch-center"]),
  row("align-items:stretch", ["flex-align-items-stretch-center"]),
  row("align-self:center", ["flex-column","flex-align-items-stretch-center"]),
  row("align-self:flex-end", ["flex-column","flex-align-items-stretch-center"]),
  row("align-self:flex-start", ["flex-column","flex-align-items-stretch-center"]),
  row("align-self:stretch", ["flex-align-items-stretch-center"]),
  row("border-bottom-style:solid", ["block-content-box-padding-border","block-border-box","flex-align-items-stretch-center"]),
  row("border-bottom-width:<length>", ["block-content-box-padding-border","block-border-box","flex-align-items-stretch-center"]),
  row("border-left-style:solid", ["block-content-box-padding-border","block-border-box","block-percent-width-padding","flex-align-items-stretch-center"]),
  row("border-left-width:<length>", ["block-content-box-padding-border","block-border-box","block-percent-width-padding","flex-align-items-stretch-center"]),
  row("border-right-style:solid", ["block-content-box-padding-border","block-border-box","flex-align-items-stretch-center"]),
  row("border-right-width:<length>", ["block-content-box-padding-border","block-border-box","flex-align-items-stretch-center"]),
  row("border-top-style:solid", ["block-content-box-padding-border","block-border-box","flex-align-items-stretch-center"]),
  row("border-top-width:<length>", ["block-content-box-padding-border","block-border-box","flex-align-items-stretch-center"]),
  row("box-sizing:border-box", ["block-border-box","block-min-max","flex-row-grow-shrink-basis"]),
  row("box-sizing:content-box", ["block-content-box-padding-border"]),
  row("column-gap:<length>", ["flex-wrap-gap-align-content","flex-justify-content"]),
  row("display:flex", ["flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","flex-justify-content","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("display:none", ["block-ua-divs"]),
  row("flex-basis:<length>", ["flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column"]),
  row("flex-basis:<percentage>", ["flex-row-grow-shrink-basis"]),
  row("flex-direction:column", ["flex-column"]),
  row("flex-direction:row", ["flex-wrap-gap-align-content"]),
  row("flex-grow:<number>", ["flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","text-ahem-single-line"]),
  row("flex-shrink:<number>", ["flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-justify-content","text-ahem-single-line"]),
  row("flex-wrap:wrap", ["flex-wrap-gap-align-content"]),
  row("font-family:Ahem", ["text-ahem-single-line"]),
  row("font-size:<length>", ["text-ahem-single-line"]),
  row("height:<length>", ["block-ua-divs","block-content-box-padding-border","block-border-box","block-percent-width-padding","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","flex-justify-content","flex-align-items-stretch-center"]),
  row("justify-content:center", ["flex-justify-content"]),
  row("justify-content:flex-end", ["flex-justify-content"]),
  row("justify-content:flex-start", ["flex-justify-content"]),
  row("justify-content:space-around", ["flex-justify-content"]),
  row("justify-content:space-between", ["flex-justify-content"]),
  row("justify-content:space-evenly", ["flex-justify-content"]),
  row("line-height:<length>", ["text-ahem-single-line"]),
  row("line-height:<number>", ["text-ahem-single-line"]),
  row("margin-bottom:<length>", ["block-content-box-padding-border","block-border-box","block-percent-width-padding","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","flex-justify-content","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("margin-left:<length>", ["block-content-box-padding-border","block-border-box","block-percent-width-padding","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","flex-justify-content","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("margin-left:<percentage>", ["block-percent-width-padding"]),
  row("margin-left:auto", ["block-auto-margin-center"]),
  row("margin-right:<length>", ["block-content-box-padding-border","block-border-box","block-percent-width-padding","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","flex-justify-content","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("margin-right:auto", ["block-auto-margin-center"]),
  row("margin-top:<length>", ["block-content-box-padding-border","block-border-box","block-percent-width-padding","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","flex-justify-content","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("margin-top:<percentage>", ["block-percent-width-padding"]),
  row("max-height:<length>", ["block-min-max","flex-align-items-stretch-center"]),
  row("max-height:<percentage>", ["block-min-max"]),
  row("max-width:<length>", ["block-min-max","flex-min-max-freeze"]),
  row("max-width:<percentage>", ["block-min-max"]),
  row("min-height:<length>", ["block-min-max","flex-align-items-stretch-center"]),
  row("min-height:<percentage>", ["block-min-max"]),
  row("min-width:<length>", ["block-min-max","flex-min-max-freeze"]),
  row("padding-bottom:<length>", ["block-content-box-padding-border","block-border-box","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-column","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("padding-bottom:<percentage>", ["block-percent-width-padding"]),
  row("padding-left:<length>", ["block-content-box-padding-border","block-border-box","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-column","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("padding-left:<percentage>", ["block-percent-width-padding"]),
  row("padding-right:<length>", ["block-content-box-padding-border","block-border-box","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-column","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("padding-right:<percentage>", ["block-percent-width-padding"]),
  row("padding-top:<length>", ["block-content-box-padding-border","block-border-box","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-column","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("padding-top:<percentage>", ["block-percent-width-padding"]),
  row("row-gap:<length>", ["flex-wrap-gap-align-content"]),
  row("width:<length>", ["block-content-box-padding-border","block-border-box","block-percent-width-padding","block-min-max","block-auto-margin-center","flex-row-grow-shrink-basis","flex-min-max-freeze","flex-column","flex-wrap-gap-align-content","flex-justify-content","flex-align-items-stretch-center","text-ahem-single-line"]),
  row("width:<percentage>", ["block-border-box","block-percent-width-padding","block-auto-margin-center"]),
  ],
};
