import type { ProfileRow, SupportProfile } from './types.ts';

// Rows name the fixtures that exercise each feature; packages/parity proves every named fixture passed the named lane in the
// same run. Layout rows are exact on the Linux lane. Colour rows are capped at caveat: chrome-dual proves the resolved channels
// (computed-value), but no lane proves native paint yet (docs/api.md §4.1). Missing rows mean unsupported.
function layout(feature: string, fixtures: readonly string[]): ProfileRow {
  return { feature, status: 'exact', proofs: [{ aspect: 'layout', lane: 'linux-dragon-layout', fixtures }] };
}

function colour(feature: string, fixtures: readonly string[]): ProfileRow {
  return { feature, status: 'caveat', proofs: [{ aspect: 'computed-value', lane: 'chrome-dual', fixtures }] };
}

export const iosProfile: SupportProfile = {
  target: 'ios',
  revision: 'm1-s2',
  rows: [
    layout("align-content:center", ["flex-wrap-gap-align-content", "flex-align-content-remaining", "flex-align-content-odd"]),
    layout("align-content:end", ["flex-align-content-remaining"]),
    layout("align-content:flex-end", ["flex-align-content-remaining", "flex-align-content-odd"]),
    layout("align-content:flex-start", ["flex-wrap-gap-align-content"]),
    layout("align-content:space-around", ["flex-align-content-remaining", "flex-align-content-odd"]),
    layout("align-content:space-between", ["flex-wrap-gap-align-content", "flex-align-content-remaining", "flex-align-content-odd"]),
    layout("align-content:space-evenly", ["flex-align-content-remaining", "flex-align-content-odd"]),
    layout("align-content:start", ["flex-align-content-remaining"]),
    layout("align-content:stretch", ["flex-align-content-remaining", "flex-align-content-odd"]),
    layout("align-items:center", ["flex-align-items-stretch-center", "flex-nested"]),
    layout("align-items:flex-start", ["flex-auto-margins-negative", "flex-intrinsic-wrap-column", "intrinsic-percent"]),
    layout("align-items:stretch", ["flex-align-items-stretch-center"]),
    layout("align-self:center", ["flex-column", "flex-align-items-stretch-center"]),
    layout("align-self:flex-end", ["flex-column", "flex-align-items-stretch-center"]),
    layout("align-self:flex-start", ["flex-column", "flex-align-items-stretch-center"]),
    layout("align-self:stretch", ["flex-align-items-stretch-center"]),
    colour("background-color:<hex-color>", ["color-syntax", "cascade-compound-variants"]),
    colour("background-color:<hsl()>", ["color-syntax"]),
    colour("background-color:<hsla()>", ["color-syntax"]),
    colour("background-color:<named-color>", ["color-syntax"]),
    colour("background-color:<rgb()>", ["color-syntax"]),
    colour("background-color:<rgba()>", ["color-syntax"]),
    colour("background-color:currentcolor", ["color-syntax"]),
    colour("background-color:initial", ["color-syntax"]),
    colour("background-color:transparent", ["color-syntax", "cascade-compound-variants"]),
    colour("border-bottom-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    colour("border-bottom-color:<named-color>", ["color-border-sides"]),
    colour("border-bottom-color:<rgb()>", ["color-border-sides"]),
    colour("border-bottom-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    colour("border-bottom-color:transparent", ["color-border-sides"]),
    colour("border-bottom-style:dashed", ["color-border-sides"]),
    colour("border-bottom-style:dotted", ["color-border-sides"]),
    colour("border-bottom-style:double", ["color-border-sides"]),
    layout("border-bottom-style:solid", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-bottom-width:<length>", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-bottom-width:thin", ["color-border-sides"]),
    colour("border-left-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    colour("border-left-color:<named-color>", ["color-border-sides"]),
    colour("border-left-color:<rgba()>", ["color-border-sides"]),
    colour("border-left-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    colour("border-left-color:inherit", ["color-border-sides"]),
    colour("border-left-style:dashed", ["color-border-sides"]),
    colour("border-left-style:dotted", ["color-border-sides"]),
    layout("border-left-style:solid", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-left-width:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-left-width:thick", ["color-border-sides"]),
    layout("border-left-width:thin", ["color-border-sides"]),
    colour("border-right-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    colour("border-right-color:<named-color>", ["color-border-sides"]),
    colour("border-right-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    colour("border-right-style:dashed", ["color-border-sides"]),
    colour("border-right-style:dotted", ["color-border-sides"]),
    layout("border-right-style:solid", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-right-width:<length>", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-right-width:thin", ["color-border-sides"]),
    colour("border-top-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    colour("border-top-color:<hsl()>", ["color-border-sides"]),
    colour("border-top-color:<named-color>", ["color-border-sides"]),
    colour("border-top-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    colour("border-top-style:dashed", ["color-border-sides"]),
    colour("border-top-style:dotted", ["color-border-sides"]),
    layout("border-top-style:solid", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-top-width:<length>", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("border-top-width:thin", ["color-border-sides"]),
    layout("box-sizing:border-box", ["block-border-box", "block-min-max", "flex-row-grow-shrink-basis", "block-fractional-values", "percent-height-chain", "flex-stretch-percent-minmax"]),
    layout("box-sizing:content-box", ["block-content-box-padding-border"]),
    colour("color:<hex-color>", ["color-syntax", "cascade-compound-variants"]),
    colour("color:<hsl()>", ["color-syntax"]),
    colour("color:<hsla()>", ["color-syntax"]),
    colour("color:<named-color>", ["color-syntax", "color-border-sides", "cascade-compound-variants"]),
    colour("color:<rgb()>", ["color-syntax"]),
    colour("color:<rgba()>", ["color-syntax"]),
    colour("color:currentcolor", ["color-border-sides"]),
    colour("color:inherit", ["color-syntax"]),
    layout("column-gap:<length>", ["flex-wrap-gap-align-content", "flex-justify-content", "color-syntax", "block-fractional-values", "flex-align-content-remaining", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "flex-nested"]),
    layout("display:flex", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "cascade-compound-variants", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("display:none", ["block-ua-divs"]),
    layout("flex-basis:<length>", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "block-fractional-values", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    layout("flex-basis:<percentage>", ["flex-row-grow-shrink-basis", "block-fractional-values", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    layout("flex-direction:column", ["flex-column", "cascade-compound-variants", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("flex-direction:row", ["flex-wrap-gap-align-content"]),
    layout("flex-grow:<number>", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "text-ahem-single-line", "cascade-compound-variants", "block-fractional-values", "flex-auto-margins-main", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    layout("flex-shrink:<number>", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-justify-content", "text-ahem-single-line", "block-fractional-values", "flex-auto-margins-negative", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    layout("flex-wrap:wrap", ["flex-wrap-gap-align-content", "color-syntax", "flex-auto-margins-cross", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column"]),
    layout("font-family:Ahem", ["text-ahem-single-line"]),
    layout("font-size:<length>", ["text-ahem-single-line"]),
    layout("height:<length>", ["block-ua-divs", "block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "margin-collapse-body", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("height:<percentage>", ["percent-height-chain", "flex-percent-definite"]),
    layout("justify-content:center", ["flex-justify-content", "flex-auto-margins-main", "flex-auto-margins-negative"]),
    layout("justify-content:flex-end", ["flex-justify-content"]),
    layout("justify-content:flex-start", ["flex-justify-content"]),
    layout("justify-content:space-around", ["flex-justify-content"]),
    layout("justify-content:space-between", ["flex-justify-content", "flex-auto-margins-main", "flex-nested"]),
    layout("justify-content:space-evenly", ["flex-justify-content", "flex-nested"]),
    layout("line-height:<length>", ["text-ahem-single-line"]),
    layout("line-height:<number>", ["text-ahem-single-line"]),
    layout("margin-bottom:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "margin-collapse-body", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("margin-bottom:<percentage>", ["block-fractional-values"]),
    layout("margin-bottom:auto", ["flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    layout("margin-left:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("margin-left:<percentage>", ["block-percent-width-padding", "block-fractional-values", "intrinsic-percent"]),
    layout("margin-left:auto", ["block-auto-margin-center", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    layout("margin-right:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("margin-right:<percentage>", ["intrinsic-percent"]),
    layout("margin-right:auto", ["block-auto-margin-center", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    layout("margin-top:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "margin-collapse-body", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("margin-top:<percentage>", ["block-percent-width-padding"]),
    layout("margin-top:auto", ["flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    layout("max-height:<length>", ["block-min-max", "flex-align-items-stretch-center", "margin-collapse-min-height"]),
    layout("max-height:<percentage>", ["block-min-max", "percent-height-chain", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("max-width:<length>", ["block-min-max", "flex-min-max-freeze", "flex-wrap-line-grow", "flex-intrinsic-wrap-column"]),
    layout("max-width:<percentage>", ["block-min-max", "intrinsic-percent", "flex-stretch-percent-minmax"]),
    layout("min-height:<length>", ["block-min-max", "flex-align-items-stretch-center", "margin-collapse-min-height"]),
    layout("min-height:<percentage>", ["block-min-max", "percent-height-chain", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("min-width:<length>", ["block-min-max", "flex-min-max-freeze", "block-fractional-values", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "flex-nested"]),
    layout("min-width:<percentage>", ["intrinsic-percent", "flex-stretch-percent-minmax"]),
    layout("padding-bottom:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "flex-intrinsic-wrap-column", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("padding-bottom:<percentage>", ["block-percent-width-padding"]),
    layout("padding-left:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "flex-intrinsic-wrap-column", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("padding-left:<percentage>", ["block-percent-width-padding", "block-fractional-values", "intrinsic-percent"]),
    layout("padding-right:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "flex-intrinsic-wrap-column", "flex-nested", "flex-stretch-percent-minmax"]),
    layout("padding-right:<percentage>", ["block-percent-width-padding", "intrinsic-percent"]),
    layout("padding-top:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-parent-child", "flex-intrinsic-wrap-column", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("padding-top:<percentage>", ["block-percent-width-padding"]),
    layout("row-gap:<length>", ["flex-wrap-gap-align-content", "color-syntax", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "flex-nested"]),
    layout("width:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    layout("width:<percentage>", ["block-border-box", "block-percent-width-padding", "block-auto-margin-center", "block-fractional-values", "percent-height-chain", "intrinsic-percent"]),
  ],
};
