// Generated by scripts/gen-profile-rows.ts (pnpm run profile:rows) from packages/parity/out/lanes.json. Do not edit.
// A native output is ready only when its target has a recorded lanes run, none stale, in which every lane passes (P6a).

/** One native target's committed lanes verdict. */
export type NativeLanesVerdict = { readonly recorded: boolean; readonly stale: readonly string[]; readonly notPassing: readonly string[] };

export const NATIVE_LANES: { readonly ios: NativeLanesVerdict; readonly android: NativeLanesVerdict } = {
  ios: { recorded: true, stale: ["packages/parity/out/lanes.json: ios layout-vectors-host does not match the configured case list", "packages/parity/out/lanes.json: ios layout-vectors-device does not match the configured case list", "packages/parity/out/lanes.json: ios device-frames does not match the configured case list", "packages/parity/out/lanes.json: ios device-applied does not match the configured case list", "packages/parity/out/lanes.json: ios device-lines does not match the configured case list", "packages/parity/out/lanes.json: ios device-pixels does not match the configured case list"], notPassing: ["device-pixels fail (546 failures (pixel 546))"] },
  android: { recorded: true, stale: ["packages/parity/out/lanes.json: android layout-vectors-host does not match the configured case list", "packages/parity/out/lanes.json: android layout-vectors-device does not match the configured case list", "packages/parity/out/lanes.json: android device-frames does not match the configured case list", "packages/parity/out/lanes.json: android device-applied does not match the configured case list", "packages/parity/out/lanes.json: android device-lines does not match the configured case list", "packages/parity/out/lanes.json: android device-pixels does not match the configured case list"], notPassing: ["device-pixels fail (1397 failures (pixel 1397))"] },
};
