// Generated by scripts/gen-profile-rows.ts (pnpm run profile:rows) from packages/parity/out/lanes.json. Do not edit.
// A native output is ready only when its target has a recorded lanes run, none stale, in which every lane passes (P6a).

/** One native target's committed lanes verdict. */
export type NativeLanesVerdict = { readonly recorded: boolean; readonly stale: readonly string[]; readonly notPassing: readonly string[] };

export const NATIVE_LANES: { readonly ios: NativeLanesVerdict; readonly android: NativeLanesVerdict } = {
  ios: { recorded: true, stale: [], notPassing: ["device-pixels fail (472 failures (pixel 472))"] },
  android: { recorded: true, stale: [], notPassing: ["device-pixels fail (1305 failures (pixel 1305))"] },
};
