import type { ProfileRow, SupportProfile } from './types.ts';

// Web output is CSS emitted from the resolved result and rendered by the reference browser itself. A row is exact only when
// the named fixtures passed the chrome-dual lane in the same run: authored and compiled renderings with equal boxes, equal
// computed values for every longhand and colour channels equal to Dragon's. Missing rows mean unsupported.
function dual(feature: string, fixtures: readonly string[]): ProfileRow {
  return {
    feature,
    status: 'exact',
    proofs: [
      { aspect: 'layout', lane: 'chrome-dual', fixtures },
      { aspect: 'computed-value', lane: 'chrome-dual', fixtures },
    ],
  };
}

function values(feature: string, fixtures: readonly string[]): ProfileRow {
  return { feature, status: 'exact', proofs: [{ aspect: 'computed-value', lane: 'chrome-dual', fixtures }] };
}

export const webProfile: SupportProfile = {
  target: 'web',
  revision: 'm1-s2',
  rows: [
    dual("align-content:center", ["flex-wrap-gap-align-content", "flex-align-content-remaining", "flex-align-content-odd"]),
    dual("align-content:end", ["flex-align-content-remaining"]),
    dual("align-content:flex-end", ["flex-align-content-remaining", "flex-align-content-odd"]),
    dual("align-content:flex-start", ["flex-wrap-gap-align-content"]),
    dual("align-content:space-around", ["flex-align-content-remaining", "flex-align-content-odd"]),
    dual("align-content:space-between", ["flex-wrap-gap-align-content", "flex-align-content-remaining", "flex-align-content-odd"]),
    dual("align-content:space-evenly", ["flex-align-content-remaining", "flex-align-content-odd"]),
    dual("align-content:start", ["flex-align-content-remaining"]),
    dual("align-content:stretch", ["flex-align-content-remaining", "flex-align-content-odd"]),
    dual("align-items:center", ["flex-align-items-stretch-center", "flex-nested"]),
    dual("align-items:flex-start", ["flex-auto-margins-negative", "flex-intrinsic-wrap-column", "intrinsic-percent"]),
    dual("align-items:stretch", ["flex-align-items-stretch-center"]),
    dual("align-self:center", ["flex-column", "flex-align-items-stretch-center"]),
    dual("align-self:flex-end", ["flex-column", "flex-align-items-stretch-center"]),
    dual("align-self:flex-start", ["flex-column", "flex-align-items-stretch-center"]),
    dual("align-self:stretch", ["flex-align-items-stretch-center"]),
    values("background-color:<hex-color>", ["color-syntax", "cascade-compound-variants"]),
    values("background-color:<hsl()>", ["color-syntax"]),
    values("background-color:<hsla()>", ["color-syntax"]),
    values("background-color:<named-color>", ["color-syntax"]),
    values("background-color:<rgb()>", ["color-syntax"]),
    values("background-color:<rgba()>", ["color-syntax"]),
    values("background-color:currentcolor", ["color-syntax"]),
    values("background-color:initial", ["color-syntax"]),
    values("background-color:transparent", ["color-syntax", "cascade-compound-variants"]),
    values("border-bottom-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    values("border-bottom-color:<named-color>", ["color-border-sides"]),
    values("border-bottom-color:<rgb()>", ["color-border-sides"]),
    values("border-bottom-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    values("border-bottom-color:transparent", ["color-border-sides"]),
    values("border-bottom-style:dashed", ["color-border-sides"]),
    values("border-bottom-style:dotted", ["color-border-sides"]),
    values("border-bottom-style:double", ["color-border-sides"]),
    dual("border-bottom-style:solid", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-bottom-width:<length>", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-bottom-width:thin", ["color-border-sides"]),
    values("border-left-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    values("border-left-color:<named-color>", ["color-border-sides"]),
    values("border-left-color:<rgba()>", ["color-border-sides"]),
    values("border-left-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    values("border-left-color:inherit", ["color-border-sides"]),
    values("border-left-style:dashed", ["color-border-sides"]),
    values("border-left-style:dotted", ["color-border-sides"]),
    dual("border-left-style:solid", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-left-width:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-left-width:thick", ["color-border-sides"]),
    dual("border-left-width:thin", ["color-border-sides"]),
    values("border-right-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    values("border-right-color:<named-color>", ["color-border-sides"]),
    values("border-right-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    values("border-right-style:dashed", ["color-border-sides"]),
    values("border-right-style:dotted", ["color-border-sides"]),
    dual("border-right-style:solid", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-right-width:<length>", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-right-width:thin", ["color-border-sides"]),
    values("border-top-color:<hex-color>", ["color-border-sides", "cascade-compound-variants"]),
    values("border-top-color:<hsl()>", ["color-border-sides"]),
    values("border-top-color:<named-color>", ["color-border-sides"]),
    values("border-top-color:currentcolor", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    values("border-top-style:dashed", ["color-border-sides"]),
    values("border-top-style:dotted", ["color-border-sides"]),
    dual("border-top-style:solid", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-top-width:<length>", ["block-content-box-padding-border", "block-border-box", "flex-align-items-stretch-center", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("border-top-width:thin", ["color-border-sides"]),
    dual("box-sizing:border-box", ["block-border-box", "block-min-max", "flex-row-grow-shrink-basis", "block-fractional-values", "percent-height-chain", "flex-stretch-percent-minmax"]),
    dual("box-sizing:content-box", ["block-content-box-padding-border"]),
    values("color:<hex-color>", ["color-syntax", "cascade-compound-variants"]),
    values("color:<hsl()>", ["color-syntax"]),
    values("color:<hsla()>", ["color-syntax"]),
    values("color:<named-color>", ["color-syntax", "color-border-sides", "cascade-compound-variants"]),
    values("color:<rgb()>", ["color-syntax"]),
    values("color:<rgba()>", ["color-syntax"]),
    values("color:currentcolor", ["color-border-sides"]),
    values("color:inherit", ["color-syntax"]),
    dual("column-gap:<length>", ["flex-wrap-gap-align-content", "flex-justify-content", "color-syntax", "block-fractional-values", "flex-align-content-remaining", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "flex-nested"]),
    dual("display:flex", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "cascade-compound-variants", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("display:none", ["block-ua-divs"]),
    dual("flex-basis:<length>", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "block-fractional-values", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    dual("flex-basis:<percentage>", ["flex-row-grow-shrink-basis", "block-fractional-values", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    dual("flex-direction:column", ["flex-column", "cascade-compound-variants", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("flex-direction:row", ["flex-wrap-gap-align-content"]),
    dual("flex-grow:<number>", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "text-ahem-single-line", "cascade-compound-variants", "block-fractional-values", "flex-auto-margins-main", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    dual("flex-shrink:<number>", ["flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-justify-content", "text-ahem-single-line", "block-fractional-values", "flex-auto-margins-negative", "flex-wrap-line-grow", "flex-nested", "flex-percent-definite"]),
    dual("flex-wrap:wrap", ["flex-wrap-gap-align-content", "color-syntax", "flex-auto-margins-cross", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column"]),
    dual("font-family:Ahem", ["text-ahem-single-line"]),
    dual("font-size:<length>", ["text-ahem-single-line"]),
    dual("height:<length>", ["block-ua-divs", "block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "margin-collapse-body", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("height:<percentage>", ["percent-height-chain", "flex-percent-definite"]),
    dual("justify-content:center", ["flex-justify-content", "flex-auto-margins-main", "flex-auto-margins-negative"]),
    dual("justify-content:flex-end", ["flex-justify-content"]),
    dual("justify-content:flex-start", ["flex-justify-content"]),
    dual("justify-content:space-around", ["flex-justify-content"]),
    dual("justify-content:space-between", ["flex-justify-content", "flex-auto-margins-main", "flex-nested"]),
    dual("justify-content:space-evenly", ["flex-justify-content", "flex-nested"]),
    dual("line-height:<length>", ["text-ahem-single-line"]),
    dual("line-height:<number>", ["text-ahem-single-line"]),
    dual("margin-bottom:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "margin-collapse-body", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("margin-bottom:<percentage>", ["block-fractional-values"]),
    dual("margin-bottom:auto", ["flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    dual("margin-left:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("margin-left:<percentage>", ["block-percent-width-padding", "block-fractional-values", "intrinsic-percent"]),
    dual("margin-left:auto", ["block-auto-margin-center", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    dual("margin-right:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("margin-right:<percentage>", ["intrinsic-percent"]),
    dual("margin-right:auto", ["block-auto-margin-center", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    dual("margin-top:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-siblings", "margin-collapse-parent-child", "margin-collapse-through", "margin-collapse-min-height", "margin-collapse-body", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("margin-top:<percentage>", ["block-percent-width-padding"]),
    dual("margin-top:auto", ["flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative"]),
    dual("max-height:<length>", ["block-min-max", "flex-align-items-stretch-center", "margin-collapse-min-height"]),
    dual("max-height:<percentage>", ["block-min-max", "percent-height-chain", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("max-width:<length>", ["block-min-max", "flex-min-max-freeze", "flex-wrap-line-grow", "flex-intrinsic-wrap-column"]),
    dual("max-width:<percentage>", ["block-min-max", "intrinsic-percent", "flex-stretch-percent-minmax"]),
    dual("min-height:<length>", ["block-min-max", "flex-align-items-stretch-center", "margin-collapse-min-height"]),
    dual("min-height:<percentage>", ["block-min-max", "percent-height-chain", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("min-width:<length>", ["block-min-max", "flex-min-max-freeze", "block-fractional-values", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "flex-nested"]),
    dual("min-width:<percentage>", ["intrinsic-percent", "flex-stretch-percent-minmax"]),
    dual("padding-bottom:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "flex-intrinsic-wrap-column", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("padding-bottom:<percentage>", ["block-percent-width-padding"]),
    dual("padding-left:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "flex-intrinsic-wrap-column", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("padding-left:<percentage>", ["block-percent-width-padding", "block-fractional-values", "intrinsic-percent"]),
    dual("padding-right:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "flex-intrinsic-wrap-column", "flex-nested", "flex-stretch-percent-minmax"]),
    dual("padding-right:<percentage>", ["block-percent-width-padding", "intrinsic-percent"]),
    dual("padding-top:<length>", ["block-content-box-padding-border", "block-border-box", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-column", "flex-align-items-stretch-center", "text-ahem-single-line", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "percent-height-chain", "margin-collapse-parent-child", "flex-intrinsic-wrap-column", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("padding-top:<percentage>", ["block-percent-width-padding"]),
    dual("row-gap:<length>", ["flex-wrap-gap-align-content", "color-syntax", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "flex-nested"]),
    dual("width:<length>", ["block-content-box-padding-border", "block-border-box", "block-percent-width-padding", "block-min-max", "block-auto-margin-center", "flex-row-grow-shrink-basis", "flex-min-max-freeze", "flex-column", "flex-wrap-gap-align-content", "flex-justify-content", "flex-align-items-stretch-center", "text-ahem-single-line", "color-syntax", "color-border-sides", "cascade-compound-variants", "block-fractional-values", "flex-auto-margins-main", "flex-auto-margins-cross", "flex-auto-margins-negative", "flex-align-content-remaining", "flex-align-content-odd", "flex-wrap-line-grow", "flex-intrinsic-wrap-column", "intrinsic-percent", "flex-nested", "flex-percent-definite", "flex-stretch-percent-minmax"]),
    dual("width:<percentage>", ["block-border-box", "block-percent-width-padding", "block-auto-margin-center", "block-fractional-values", "percent-height-chain", "intrinsic-percent"]),
  ],
};
