// Interop focus areas: the interop-YYYY-<area> labels in web-platform-tests/wpt-metadata META.yml files, pinned in wpt.lock. The
// committed map (interop-labels.json) holds CSS test files only; labels with no CSS test are listed as excluded.
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Entry, Expectations } from './expectations.ts';
import { lockedMetadataCommit, packagePath } from './paths.ts';

export type LabelledTest = { readonly label: string; readonly test: string };

const unquote = (v: string): string => {
  const t = v.trim();
  return (t.startsWith("'") && t.endsWith("'")) || (t.startsWith('"') && t.endsWith('"')) ? t.slice(1, -1) : t;
};

/**
 * The (label, test) pairs of one META.yml: each item of its top-level "links" sequence may carry a label and a results sequence
 * of { test, subtest?, status? } entries. Indentation decides nesting, as in YAML block sequences.
 */
export function readMetaYml(text: string): LabelledTest[] {
  const out: LabelledTest[] = [];
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((l) => /^links:\s*$/.test(l));
  if (start < 0) return out;
  let linkIndent = -1;
  let keyIndent = -1;
  let label: string | null = null;
  let tests: string[] = [];
  const flush = (): void => {
    if (label !== null) for (const t of tests) out.push({ label, test: t });
    label = null;
    tests = [];
  };
  for (const raw of lines.slice(start + 1)) {
    if (raw.trim() === '' || raw.trim().startsWith('#')) continue;
    const indent = raw.length - raw.trimStart().length;
    const dash = /^(\s*)-\s+(.*)$/.exec(raw);
    if (indent === 0 && dash === null) break;
    if (linkIndent < 0 && dash !== null) linkIndent = indent;
    let body = raw.trim();
    if (dash !== null && indent === linkIndent) {
      flush();
      body = dash[2] as string;
      keyIndent = raw.length - body.length;
    } else if (dash !== null) {
      const m = /^test:\s*(.*)$/.exec(dash[2] as string);
      if (m !== null) tests.push(unquote(m[1] as string));
      continue;
    } else if (indent !== keyIndent) continue;
    const kv = /^([\w-]+):\s*(.*)$/.exec(body);
    if (kv !== null && kv[1] === 'label') label = unquote(kv[2] as string);
  }
  flush();
  return out;
}

/** The test file a WPT test id names: variants dropped, .any/.window/.worker test ids mapped back to their .js file. */
export function testFileOf(id: string): string {
  const path = id.replace(/[?#].*$/, '');
  const m = /^(.*?)\.(any(?:\.[a-z]+)?|window|worker)\.html$/.exec(path);
  if (m === null) return path;
  return m[2]?.startsWith('any') ? `${m[1]}.any.js` : `${m[1]}.${m[2]}.js`;
}

export type InteropLabels = {
  readonly wptMetadata: string;
  readonly note: string;
  /** CSS-bearing labels to their sorted CSS test files (css/...). */
  readonly labels: { readonly [label: string]: readonly string[] };
  /** Labels whose tests are all outside css/, with their test file count; they are not scored. */
  readonly excluded: { readonly [label: string]: number };
  /** Per CSS-bearing label: test files outside css/ that the label also names, not scored here. */
  readonly nonCssFiles: { readonly [label: string]: number };
};

const byCodeUnit = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

export const INTEROP_NOTE = 'Interop focus-area labels (interop-YYYY-*) from web-platform-tests/wpt-metadata META.yml files, CSS test files only; generated by pnpm wpt:interop-labels.';

/** Derives the label map from a wpt-metadata checkout: every META.yml, interop-* labels only. */
export function deriveInteropLabels(checkout: string, commit: string): InteropLabels {
  const byLabel = new Map<string, Set<string>>();
  const walk = (dir: string, rel: string): void => {
    for (const d of readdirSync(dir, { withFileTypes: true })) {
      if (d.name === '.git') continue;
      const r = rel === '' ? d.name : `${rel}/${d.name}`;
      if (d.isDirectory()) walk(join(dir, d.name), r);
      else if (d.name === 'META.yml') {
        for (const { label, test } of readMetaYml(readFileSync(join(dir, d.name), 'utf8'))) {
          if (!/^interop-\d{4}-/.test(label)) continue;
          if (test.includes('*')) throw new Error(`${r}: wildcard test ${JSON.stringify(test)} under ${label} is not expanded by this generator`);
          const set = byLabel.get(label) ?? new Set<string>();
          set.add(testFileOf(rel === '' ? test : `${rel}/${test}`));
          byLabel.set(label, set);
        }
      }
    }
  };
  walk(checkout, '');
  const labels: Record<string, string[]> = {};
  const excluded: Record<string, number> = {};
  const nonCssFiles: Record<string, number> = {};
  for (const label of [...byLabel.keys()].sort(byCodeUnit)) {
    const files = [...(byLabel.get(label) as Set<string>)];
    const css = files.filter((f) => f.startsWith('css/')).sort(byCodeUnit);
    if (css.length === 0) excluded[label] = files.length;
    else {
      labels[label] = css;
      if (files.length > css.length) nonCssFiles[label] = files.length - css.length;
    }
  }
  return { wptMetadata: commit, note: INTEROP_NOTE, labels, excluded, nonCssFiles };
}

export function checkoutCommit(checkout: string): string {
  return execFileSync('git', ['-C', checkout, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
}

export const interopLabelsPath = (): string => packagePath('interop-labels.json');

export function serializeInteropLabels(l: InteropLabels): string {
  return `${JSON.stringify({ excluded: l.excluded, labels: l.labels, nonCssFiles: l.nonCssFiles, note: l.note, wptMetadata: l.wptMetadata }, null, 1)}\n`;
}

/** The committed label map, checked against the wpt-metadata commit in wpt.lock. */
export function loadInteropLabels(): InteropLabels {
  const l = JSON.parse(readFileSync(interopLabelsPath(), 'utf8')) as InteropLabels;
  const pinned = lockedMetadataCommit();
  if (l.wptMetadata !== pinned) throw new Error(`packages/wpt/interop-labels.json is from wpt-metadata ${l.wptMetadata}, but wpt.lock pins ${pinned}: run pnpm wpt:interop-labels`);
  return l;
}

/** Test file path to its sorted interop labels. */
export function labelsByPath(l: InteropLabels): ReadonlyMap<string, readonly string[]> {
  const out = new Map<string, string[]>();
  for (const label of Object.keys(l.labels).sort(byCodeUnit)) {
    for (const p of l.labels[label] as readonly string[]) {
      const list = out.get(p) ?? [];
      list.push(label);
      out.set(p, list);
    }
  }
  return out;
}

/** One Interop focus area's score on its CSS test files: Dragon's passes for the target, and Chrome's on the files it ran. */
export type AreaScore = {
  readonly label: string;
  /** The label's CSS test files present at the pinned WPT commit, and those it names that the commit does not have. */
  readonly files: number;
  readonly absent: number;
  readonly dragonPass: number;
  /** Files Chrome 145 ran in this lane (the files Dragon runs), and those where the harness was OK and every subtest passed. */
  readonly chromeRun: number;
  readonly chromePass: number;
};

const chromePasses = (x: Entry | undefined): boolean =>
  x !== undefined && x.status !== 'not-runnable' && x.chrome !== null && x.chrome.harness === 0 && x.chrome.subtests.pass === x.chrome.subtests.total;

function score(label: string, paths: readonly string[], e: Expectations): AreaScore {
  const present = paths.filter((p) => e.tests[p] !== undefined);
  return {
    label,
    files: present.length,
    absent: paths.length - present.length,
    dragonPass: present.filter((p) => e.tests[p]?.status === 'pass').length,
    chromeRun: present.filter((p) => { const x = e.tests[p]; return x !== undefined && x.status !== 'not-runnable' && x.chrome !== null; }).length,
    chromePass: present.filter((p) => chromePasses(e.tests[p])).length,
  };
}

/** Per CSS-bearing label, and overall over the union of their files, from an expectations file alone (so it is deterministic). */
export function interopScores(e: Expectations, l: InteropLabels): { readonly areas: readonly AreaScore[]; readonly overall: AreaScore } {
  const labels = Object.keys(l.labels).sort(byCodeUnit);
  const areas = labels.map((label) => score(label, l.labels[label] as readonly string[], e));
  const union = [...new Set(labels.flatMap((label) => l.labels[label] as readonly string[]))].sort(byCodeUnit);
  return { areas, overall: score(`Interop CSS (${labels.length} areas, 2021-2026)`, union, e) };
}

/** Differences in Dragon's per-area scores between the committed expectations and a recomputed run. */
export function compareInteropScores(expected: Expectations, actual: Expectations, l: InteropLabels): string[] {
  const a = interopScores(actual, l);
  const e = interopScores(expected, l);
  const out: string[] = [];
  [...e.areas, e.overall].forEach((x, i) => {
    const y = [...a.areas, a.overall][i] as AreaScore;
    if (x.dragonPass !== y.dragonPass || x.files !== y.files) out.push(`Interop ${x.label}: Dragon ${expected.target} expected ${x.dragonPass}/${x.files}, got ${y.dragonPass}/${y.files}`);
  });
  return out;
}

const pct = (n: number, d: number): string => (d === 0 ? '0.0%' : `${((100 * n) / d).toFixed(1)}%`);

/** The Interop section of summary.md. */
export function interopMarkdown(e: Expectations, l: InteropLabels): string[] {
  const { areas, overall } = interopScores(e, l);
  const mean = areas.length === 0 ? 0 : areas.reduce((s, a) => s + (a.files === 0 ? 0 : a.dragonPass / a.files), 0) / areas.length;
  const excluded = Object.entries(l.excluded).sort(([x], [y]) => byCodeUnit(x, y));
  const partial = Object.entries(l.nonCssFiles).sort(([x], [y]) => byCodeUnit(x, y));
  return [
    `## Interop focus areas (wpt-metadata \`${l.wptMetadata}\`)`,
    '',
    `**${overall.label}: Dragon ${e.target} ${overall.dragonPass}/${overall.files}; Chrome 145 ${overall.chromePass}/${overall.chromeRun} on the files this lane ran in Chrome. Mean area score for Dragon ${e.target}: ${pct(mean, 1)}.**`,
    '',
    `Each area counts its CSS test files at the pinned WPT commit. Dragon passes a file when every check-layout subtest passes; every other file (not runnable, or another kind) counts as not passing. Chrome 145 runs only where Dragon runs, so its column is pass/run, not the area's Interop score on wpt.fyi.`,
    '',
    '| area | CSS files | Dragon web | Chrome 145 (pass/run) |',
    '|---|---:|---:|---:|',
    ...areas.map((a) => `| ${a.label} | ${a.files}${a.absent > 0 ? ` (+${a.absent} absent at this commit)` : ''} | ${a.dragonPass}/${a.files} | ${a.chromePass}/${a.chromeRun} |`),
    '',
    `Excluded, no CSS test files (${excluded.length} labels): ${excluded.map(([k, n]) => `${k} (${n})`).join(', ')}.`,
    '',
    `Areas that also name non-CSS files, not scored here: ${partial.map(([k, n]) => `${k} (${n})`).join(', ')}.`,
    '',
  ];
}
