// Generated by scripts/capture-form-data.ts from Chrome 145.0.7632.6; do not edit. Regenerate with the script.
// The devolve probe (R11): at DPR 2, each control's pixels at its centre, border and corner points against a div twin
// that has the control's computed background and border. 'css' means every point matched (the control is painted as CSS boxes);
// 'theme' means the platform theme painted it. Blink rule: layout_theme.cc LayoutTheme::AdjustAppearanceWithAuthorStyle and
// IsControlStyled (push button: author background or border devolves; slider: never), at Chrome 145.0.7632.6.
export const APPEARANCE_PROBE = {
  "button": {
    "none": "theme",
    "background-color": "css",
    "border": "css",
    "appearance-none": "css"
  },
  "range": {
    "none": "theme",
    "background-color": "theme",
    "border": "theme",
    "appearance-none": "css",
    "input-none-thumb-auto": "theme"
  }
} as const;
