// Generated by scripts/capture-form-data.ts from Chrome 145.0.7632.6; do not edit. Regenerate with the script.
// The user-agent shadow tree of input[type=range]: a container div (flex), the track div (id "track", pseudo
// -webkit-slider-runnable-track, block) and the thumb div (id "thumb", pseudo -webkit-slider-thumb, block), from
// DOM.getDocument({pierce: true}). Rules are the user-agent-origin matches of CSS.getMatchedStylesForNode, in cascade order,
// as [property, value, important]. RANGE_THEME_THUMB is the thumb size LayoutTheme::AdjustSliderThumbSize gives an
// appearance:auto thumb with no author size; RANGE_NONE_THUMB is the size of an appearance:none thumb (in an appearance:none input) with no author size (CSS px).
export const RANGE_UA_SHADOW = {
  "container": [
    {
      "selectors": [
        "div"
      ],
      "declarations": [
        [
          "display",
          "block",
          false
        ]
      ]
    },
    {
      "selectors": [
        "div"
      ],
      "declarations": [
        [
          "unicode-bidi",
          "isolate",
          false
        ]
      ]
    },
    {
      "selectors": [
        "input[type=\"range\" i]::-webkit-slider-container"
      ],
      "declarations": [
        [
          "appearance",
          "inherit",
          false
        ],
        [
          "flex-grow",
          "1",
          false
        ],
        [
          "flex-shrink",
          "1",
          false
        ],
        [
          "flex-basis",
          "0%",
          false
        ],
        [
          "min-inline-size",
          "0px",
          false
        ],
        [
          "box-sizing",
          "border-box",
          false
        ],
        [
          "display",
          "flex",
          false
        ],
        [
          "-webkit-user-modify",
          "read-only !important",
          true
        ]
      ]
    }
  ],
  "track": [
    {
      "selectors": [
        "div"
      ],
      "declarations": [
        [
          "display",
          "block",
          false
        ]
      ]
    },
    {
      "selectors": [
        "div"
      ],
      "declarations": [
        [
          "unicode-bidi",
          "isolate",
          false
        ]
      ]
    },
    {
      "selectors": [
        "input[type=\"range\" i]::-webkit-slider-runnable-track"
      ],
      "declarations": [
        [
          "flex-grow",
          "1",
          false
        ],
        [
          "flex-shrink",
          "1",
          false
        ],
        [
          "flex-basis",
          "0%",
          false
        ],
        [
          "min-inline-size",
          "0px",
          false
        ],
        [
          "align-self",
          "center",
          false
        ],
        [
          "box-sizing",
          "border-box",
          false
        ],
        [
          "display",
          "block",
          false
        ],
        [
          "-webkit-user-modify",
          "read-only !important",
          true
        ]
      ]
    }
  ],
  "thumb": [
    {
      "selectors": [
        "div"
      ],
      "declarations": [
        [
          "display",
          "block",
          false
        ]
      ]
    },
    {
      "selectors": [
        "div"
      ],
      "declarations": [
        [
          "unicode-bidi",
          "isolate",
          false
        ]
      ]
    },
    {
      "selectors": [
        "input[type=\"range\" i]::-webkit-slider-thumb"
      ],
      "declarations": [
        [
          "appearance",
          "auto",
          false
        ],
        [
          "box-sizing",
          "border-box",
          false
        ],
        [
          "display",
          "block",
          false
        ],
        [
          "-webkit-user-modify",
          "read-only !important",
          true
        ]
      ]
    }
  ]
} as const;

export const RANGE_THEME_THUMB = {"width":16,"height":16} as const;

export const RANGE_NONE_THUMB = {"width":129,"height":0} as const;
