// The public API shared by the package entry (index.ts) and the internal entry (internal.ts); createProject is index.ts's own.
export type {
  ArtifactState,
  Assignment,
  AttributeBinding,
  BranchNode,
  CallNode,
  CheckReport,
  Choice,
  ClassBinding,
  ClassSymbol,
  Compiled,
  ComponentDefinition,
  Condition,
  Configured,
  Dependency,
  Diagnostic,
  DiagnosticCode,
  DocumentEntry,
  DraftTree,
  ElementNode,
  ExplainedCase,
  ExplainQuery,
  ExplainResult,
  Fix,
  FrontEndResult,
  NormalizedTarget,
  FontMap,
  FontMapEntry,
  GeneratedAsset,
  GeneratedFile,
  GenericKey,
  PinnedFace,
  ProjectConfig,
  Origin,
  Param,
  ProducerDiagnostic,
  Project,
  ProjectionNode,
  ProofRef,
  Range,
  Scalar,
  SourceFile,
  SourceRef,
  SourceSnapshot,
  Span,
  State,
  StateAlias,
  StateRef,
  StyleUse,
  SupportAnswer,
  SupportCandidate,
  SupportQuery,
  SupportStatus,
  Target,
  Targets,
  TextNode,
  TreeNode,
} from './types.ts';
export { formatDiagnostic, formatDiagnostics } from './diagnostics/format.ts';
export { querySupport } from './support.ts';
export { TREE_SCHEMA_REVISION } from './analysis/input.ts';
