// Public entry of the `dragon` package (docs/api.md §1-§2, §6.1). Internal helpers live in internal.ts behind the dragon-internal condition.
export type {
  ArtifactState,
  Assignment,
  AttributeBinding,
  BranchNode,
  CallNode,
  CheckReport,
  Choice,
  ClassBinding,
  ClassSymbol,
  Compiled,
  ComponentDefinition,
  Condition,
  Configured,
  Dependency,
  Diagnostic,
  DiagnosticCode,
  DocumentEntry,
  DraftTree,
  ElementNode,
  ExplainedCase,
  ExplainQuery,
  ExplainResult,
  Fix,
  FrontEndResult,
  GeneratedFile,
  Origin,
  Param,
  ProducerDiagnostic,
  Project,
  ProjectionNode,
  ProofRef,
  Range,
  Scalar,
  SourceFile,
  SourceRef,
  SourceSnapshot,
  Span,
  State,
  StateAlias,
  StateRef,
  StyleUse,
  SupportStatus,
  Target,
  Targets,
  TextNode,
  TreeNode,
} from './types.ts';
export { createProject } from './project.ts';
export { formatDiagnostic } from './diagnostics/format.ts';
export { TREE_SCHEMA_REVISION } from './analysis/input.ts';
