// Profile rows derived from a parity run (M1): the single definition used by scripts/gen-profile-rows.ts and by the
// committed profile-proof test in parity.test.ts.
import type { Longhand, ProfileRow, Proof } from 'dragon';
import { PROPERTY_ASPECTS } from 'dragon';
import type { CaseOutcome } from './pipeline.ts';

export const PROFILE_REVISION = 'm1-s5';

type Lane = 'linux-dragon-layout' | 'chrome-dual';
export type ProfileTarget = 'ios' | 'android' | 'web';

// Android takes the iOS keys: the compiler gives every native target one used-key set per case (project.ts features).
const keysOf = (target: ProfileTarget, c: CaseOutcome): readonly string[] => (target === 'web' ? c.features.web : c.features.ios);

/**
 * The rows for one target from the cases of one run: exactly the passing cases that use each key, per lane. Android follows the
 * iOS rule (docs/research/native-strategy.md 3.9 item 13): both natives share one layout projection and one lowered program.
 */
export function deriveRows(target: ProfileTarget, cases: readonly CaseOutcome[]): ProfileRow[] {
  const keys = [...new Set(cases.flatMap((c) => keysOf(target, c)))].sort();
  const rows: ProfileRow[] = [];
  for (const key of keys) {
    const at = key.lastIndexOf('@');
    const feature = key.slice(0, at);
    const context = key.slice(at + 1);
    const colon = feature.indexOf(':');
    const property = feature.slice(0, colon) as Longhand;
    const valueSubset = feature.slice(colon + 1);
    const aspects = PROPERTY_ASPECTS[property];
    const passing = (lane: Lane): string[] => cases.filter((c) => c.lanes[lane] === 'pass' && keysOf(target, c).includes(key)).map((c) => c.id);
    const proof = (aspect: Proof['aspect'], lane: Lane, ids: readonly string[]): Proof => ({ aspect, lane, valueSubset, context, cases: ids });
    const proofs: Proof[] = [];
    if (target !== 'web') {
      const layout = passing('linux-dragon-layout');
      const dual = passing('chrome-dual');
      if (aspects.layout && layout.length === 0) continue;
      if (aspects.paint && dual.length === 0) continue;
      if (aspects.layout) proofs.push(proof('layout', 'linux-dragon-layout', layout));
      if (aspects.paint) proofs.push(proof('computed-value', 'chrome-dual', dual));
      // No lane renders native paint in milestone 1, so a row with any paint aspect is capped at caveat.
      rows.push({ feature, context, status: aspects.paint ? 'caveat' : 'exact', proofs });
    } else {
      const dual = passing('chrome-dual');
      if (dual.length === 0) continue;
      if (aspects.layout) proofs.push(proof('layout', 'chrome-dual', dual));
      proofs.push(proof('computed-value', 'chrome-dual', dual));
      // A family left to the platform in the font map is caveat (fonts/font-map.ts supportOf): its face is the host's.
      rows.push({ feature, context, status: feature === 'font-family:<platform>' ? 'caveat' : 'exact', proofs });
    }
  }
  return rows;
}

export function profileSource(target: ProfileTarget, rows: readonly ProfileRow[]): string {
  const name = `${target}Profile`;
  const q = (s: string): string => JSON.stringify(s);
  const lines = rows.map((r) => {
    const proofs = r.proofs.map((p) => `{ aspect: ${q(p.aspect)}, lane: ${q(p.lane)}, valueSubset: ${q(p.valueSubset)}, context: ${q(p.context)}, cases: [${p.cases.map(q).join(', ')}] }`);
    return `    { feature: ${q(r.feature)}, context: ${q(r.context)}, status: ${q(r.status)}, proofs: [${proofs.join(', ')}] },`;
  });
  return [
    '// Generated by scripts/gen-profile-rows.ts (pnpm run profile:rows) from the parity cases that passed each proof\'s lane',
    '// against the committed captures. Do not edit. Missing rows mean unsupported.',
    "import type { SupportProfile } from './types.ts';",
    '',
    `export const ${name}: SupportProfile = {`,
    `  target: ${q(target)},`,
    `  revision: ${q(PROFILE_REVISION)},`,
    '  rows: [',
    ...lines,
    '  ],',
    '};',
    '',
  ].join('\n');
}
