// The Android Views backend emitter (notes/T013-p3-review-p4-plan.md section 2 item 2): Kotlin, one input function and one
// view-building function per case, from the lowered program alone. The input is typed constructor calls of the translated engine;
// the build function creates the Dragon views and writes each property of the program in Android vocabulary. Values that depend on
// the device scale (View.layout ints, border widths, the clip bounds, the text instance size and line boxes) are applied by
// DragonTree from the translated engine at the device density. No stylesheet, selector, class name or JSON is emitted.
import type { GeneratedFile } from '../types.ts';
import type { ProgramNode, ProgramWrite } from '../lower/native-program.ts';
import { PROGRAM_VERSIONS } from '../lower/native-program.ts';
import type { EmitCase } from './native-support.ts';
import { chunks, doubleLit, environmentArgs, inputFunctions, stringLit, supportDigest } from './native-support.ts';
import { isPaintKind, paintWriteLines } from './paint/registry.ts';

export const ANDROID_VIEWS_EMITTER_VERSION = 'dragon.android-views-emitter/1';
export const KOTLIN_CASES_PACKAGE = 'dev.dragon.cases';
const CASES_PER_FILE = 10;
const NODES_PER_FUNCTION = 12;

const q = (s: string): string => stringLit('kotlin', s);
const rgba = (c: { r: number; g: number; b: number; alpha: number }): string => `DragonRGBA8(${c.r}, ${c.g}, ${c.b}, ${c.alpha})`;

function writeLines(v: string, n: ProgramNode, w: ProgramWrite): string[] {
  if (isPaintKind(w.kind)) return paintWriteLines('android-views', v, n, w);
  switch (w.kind) {
    case 'font': {
      const color = n.writes.find((x) => x.kind === 'text-color');
      if (color === undefined || color.kind !== 'text-color') throw new Error(`${n.id}: a text run without a colour`);
      return [`  ${v}.dragonSetText(${q(n.text ?? '')}, ${q(w.font.family)}, ${rgba(color.color)})`];
    }
    case 'text-color':
      return [`  // ${w.key}: set with the text run above`];
  }
  throw new Error(`${n.id}: write kind ${w.kind} has no Android Views lines`);
}

function caseSource(c: EmitCase, k: number): string {
  const input = inputFunctions('kotlin', c.program.root, `case${k}`);
  const nodes = c.program.nodes.map((n, i) => {
    const v = `v${i}`;
    const parent = n.parent === null ? 'null' : q(n.parent);
    const host = n.host === n.parent || n.host === null ? [] : [`  t.host(${q(n.id)}, ${q(n.host)})`];
    return [`  val ${v} = t.${n.kind === 'text' ? 'textNode' : 'boxNode'}(${q(n.id)}, ${parent}, ${q(n.kind)})`, ...host, ...n.writes.flatMap((w) => writeLines(v, n, w))];
  });
  const parts = chunks(nodes, NODES_PER_FUNCTION);
  const digests = c.expectedDigests.map((d) => `${doubleLit(d.dpr)} to ${q(d.sha256)}`).join(', ');
  return [
    `// case ${c.id}`,
    ...input.decls,
    ...parts.map((part, j) => [`private fun case${k}Build${j}(t: DragonTree) {`, ...part.flat(), '}'].join('\n')),
    `/** Builds the native tree of case ${c.id}. */`,
    `private fun case${k}Build(t: DragonTree) {`,
    ...parts.map((_, j) => `  case${k}Build${j}(t)`),
    '}',
    `private fun case${k}Input(dpr: Double): LayoutInput = LayoutInput(Viewport(${doubleLit(c.viewport.width)}, ${doubleLit(c.viewport.height)}), dpr, ${environmentArgs(c.viewport, c.program.rootFontSize)}, ${input.root})`,
    `val dragonCase${k} = DragonCase(${q(c.id)}, ${q(c.fixture)}, ${q(c.direction)}, ${q(c.compilerDigest)}, ${doubleLit(c.viewport.width)}, ${doubleLit(c.viewport.height)}, mapOf(${digests}), ::case${k}Input, ::case${k}Build)`,
  ].join('\n');
}

/** The generated Kotlin case files and the case table, in case order. */
export function emitAndroidViewsCases(cases: readonly EmitCase[]): GeneratedFile[] {
  const header = `// GENERATED by dragon emit/android-views.ts (${ANDROID_VIEWS_EMITTER_VERSION}; program ${PROGRAM_VERSIONS['android-views']}; support ${supportDigest('android-views')}). Do not edit.\npackage ${KOTLIN_CASES_PACKAGE}\n\nimport dev.dragon.layout.*\nimport dev.dragon.views.*\n\n`;
  const out: GeneratedFile[] = [];
  for (let f = 0; f * CASES_PER_FILE < cases.length; f++) {
    const chunk = cases.slice(f * CASES_PER_FILE, (f + 1) * CASES_PER_FILE);
    out.push({ path: `kotlin/dev/dragon/cases/DragonCases${String(f).padStart(3, '0')}.kt`, text: `${header}${chunk.map((c, i) => caseSource(c, f * CASES_PER_FILE + i)).join('\n\n')}\n` });
  }
  out.push({
    path: 'kotlin/dev/dragon/cases/DragonCaseTable.kt',
    text: `${header}/** Every layout case, in case order. */\nval dragonCaseList: List<DragonCase> by lazy { listOf(${cases.map((_, k) => `dragonCase${k}`).join(', ')}) }\n\nval dragonCaseTable: Map<String, DragonCase> by lazy { dragonCaseList.associateBy { it.id } }\n`,
  });
  return out;
}
