// The UIKit backend emitter (notes/T013-p3-review-p4-plan.md section 2 item 2): Swift, one input function and one view-building
// function per case, from the lowered program alone. The input is typed constructor calls of the translated engine; the build
// function creates the Dragon views and writes each property of the program in UIKit vocabulary. Values that depend on the device
// scale (frames, border widths, the clip frame, the text instance size and line boxes) are applied by DragonTree from the
// translated engine at the device scale. No stylesheet, selector, class name or JSON is emitted.
import type { GeneratedFile } from '../types.ts';
import type { ProgramNode, ProgramWrite } from '../lower/native-program.ts';
import { PROGRAM_VERSIONS } from '../lower/native-program.ts';
import type { EmitCase } from './native-support.ts';
import { chunks, doubleLit, inputFunctions, stringLit, supportDigest } from './native-support.ts';

export const UIKIT_EMITTER_VERSION = 'dragon.uikit-emitter/1';
const CASES_PER_FILE = 10;
const NODES_PER_FUNCTION = 12;

const q = (s: string): string => stringLit('swift', s);
const rgba = (c: { r: number; g: number; b: number; alpha: number }): string => `DragonRGBA8(${c.r}, ${c.g}, ${c.b}, ${c.alpha})`;

function writeLines(v: string, n: ProgramNode, w: ProgramWrite): string[] {
  switch (w.kind) {
    case 'background-color':
      return [`  ${v}.backgroundColor = dragonUIColor(${rgba(w.color)})`];
    case 'border-widths':
      return [`  // ${w.key}: from the translated engine at the device scale (DragonTree.apply)`];
    case 'border-styles':
      return [`  ${v}.dragonBorderStyles = [${w.styles.map(q).join(', ')}]`];
    case 'border-colors':
      return [`  ${v}.dragonBorderColors = [${w.colors.map(rgba).join(', ')}]`];
    case 'padding-box-clip':
      return [`  ${v}.dragonEnableClip()`];
    case 'font': {
      const color = n.writes.find((x) => x.kind === 'text-color');
      if (color === undefined || color.kind !== 'text-color') throw new Error(`${n.id}: a text run without a colour`);
      return [`  ${v}.dragonSetText(${q(n.text ?? '')}, family: ${q(w.family)}, cssSize: ${doubleLit(w.size)}, color: ${rgba(color.color)})`];
    }
    case 'text-color':
      return [`  // ${w.key}: set with the text run above`];
  }
}

function caseSource(c: EmitCase, k: number): string {
  const input = inputFunctions('swift', c.program.root, `dragonCase${k}`);
  const nodes = c.program.nodes.map((n, i) => {
    const v = `v${i}`;
    const parent = n.parent === null ? 'nil' : q(n.parent);
    return [`  let ${v} = t.${n.kind === 'text' ? 'textNode' : 'boxNode'}(${q(n.id)}, parent: ${parent}, kind: ${q(n.kind)})`, ...n.writes.flatMap((w) => writeLines(v, n, w))];
  });
  const parts = chunks(nodes, NODES_PER_FUNCTION);
  const digests = c.expectedDigests.map((d) => `${doubleLit(d.dpr)}: ${q(d.sha256)}`).join(', ');
  return [
    `// case ${c.id}`,
    ...input.decls,
    ...parts.map((part, j) => [`private func dragonCase${k}Build${j}(_ t: DragonTree) {`, ...part.flat(), '}'].join('\n')),
    `/// Builds the native tree of case ${c.id}.`,
    `func dragonCase${k}Build(_ t: DragonTree) {`,
    ...parts.map((_, j) => `  dragonCase${k}Build${j}(t)`),
    '}',
    `func dragonCase${k}Input(_ dpr: Double) -> LayoutInput {`,
    `  return LayoutInput(Viewport(${doubleLit(c.viewport.width)}, ${doubleLit(c.viewport.height)}), dpr, ${input.root})`,
    '}',
    `let dragonCase${k} = DragonCase(id: ${q(c.id)}, fixture: ${q(c.fixture)}, direction: ${q(c.direction)}, compilerDigest: ${q(c.compilerDigest)}, viewport: (width: ${doubleLit(c.viewport.width)}, height: ${doubleLit(c.viewport.height)}), expectedDigests: [${digests}], input: dragonCase${k}Input, build: dragonCase${k}Build)`,
  ].join('\n');
}

/** The generated Swift case files and the case table, in case order. */
export function emitUikitCases(cases: readonly EmitCase[]): GeneratedFile[] {
  const header = `// GENERATED by dragon emit/uikit.ts (${UIKIT_EMITTER_VERSION}; program ${PROGRAM_VERSIONS.uikit}; support ${supportDigest('uikit')}). Do not edit.\nimport UIKit\n\n`;
  const out: GeneratedFile[] = [];
  for (let f = 0; f * CASES_PER_FILE < cases.length; f++) {
    const chunk = cases.slice(f * CASES_PER_FILE, (f + 1) * CASES_PER_FILE);
    out.push({ path: `Cases/DragonCases${String(f).padStart(3, '0')}.swift`, text: `${header}${chunk.map((c, i) => caseSource(c, f * CASES_PER_FILE + i)).join('\n\n')}\n` });
  }
  out.push({
    path: 'Cases/DragonCaseTable.swift',
    text: `${header}/// Every layout case, in case order.\npublic let dragonCaseList: [DragonCase] = [${cases.map((_, k) => `dragonCase${k}`).join(', ')}]\n\npublic let dragonCaseTable: [String: DragonCase] = Dictionary(uniqueKeysWithValues: dragonCaseList.map { ($0.id, $0) })\n`,
  });
  return out;
}
