export type * from './input.ts';
export type { LU, FactorSum } from './units.ts';
export { fromCssPx, fromRaw, toPx, LU_PER_PX } from './units.ts';
export type { LayoutRect, LayoutResult } from './layout.ts';
export { layout, layoutWithFaults, absoluteRects } from './layout.ts';
export type { EngineFaults } from './block.ts';
export { NO_ENGINE_FAULTS } from './block.ts';
export type { LayoutUnsupported, UnsupportedCode } from './unsupported.ts';
export type { FontMetrics, MeasureResult, TextMeasure, TextMeasurer } from './text.ts';
export { ahemMeasurer } from './text.ts';
export type { ValidationError, ValidationErrorCode, ValidationResult } from './validate.ts';
export { validateLayoutInput } from './validate.ts';
export type { ChromeDeviation } from './chrome-deviations.ts';
export { chromeDeviations } from './chrome-deviations.ts';
export type { PlatformRule } from './platform-rules.ts';
export { platformRules } from './platform-rules.ts';
export type { DeviationFault } from './chrome-deviations.ts';
export { PLATFORM_RULES } from './platform-rules.ts';
export type { MeasurerChoice } from './platform.ts';
export { measurerFor, REFERENCE_PLATFORM } from './platform.ts';
export type { SnappedRect } from './snap.ts';
export { snapEdges, snapRect } from './snap.ts';
// Replaced elements (REPL-a): sizing and the object-fit destination rect.
export type { BorderPadding, InlineAutoBehavior, NaturalSizing, ObjectFit, ObjectPosition, ObjectRect, PixelRect, ReplacedSize, ReplacedSizeMode, ReplacedSpace } from './replaced.ts';
export { blockFlowSpace, drawnObjectRect, objectFitRect, pixelSnappedRect, replacedAspectRatio, replacedSize } from './replaced.ts';
export type { ReplacedPaint } from './paint.ts';
export { replacedPaint } from './paint.ts';
export type { DprChromeDeviation, DprDeviationControl, DprDeviationFault, DprDeviationNode } from './chrome-deviations-dpr.ts';
export { dprChromeDeviations } from './chrome-deviations-dpr.ts';
export type { AhemRuleFaults, FontData } from './text.ts';
export { AHEM_FONT_DATA, ahemMeasurerWith, coveredCodePoints, coveredIndex, fontDataMeasurer } from './text.ts';
export { zoomInput } from './layout.ts';
export type { Edges } from './box.ts';
export { resolveBorder } from './box.ts';
export { platformFontSize, snapEdge, zoomFontSize } from './units.ts';
export type { LinePiece, PlacedLine } from './inline.ts';
export { placeLines } from './inline.ts';
export type { Ctx } from './block.ts';
export { resolvePadding } from './box.ts';
export type { DprPlatformRule, DprPlatformRuleNode } from './platform-rules.ts';
export { dprPlatformRules } from './platform-rules.ts';
export type { CalcClamp, CalcExpr, CalcInvert, CalcMax, CalcMin, CalcProduct, CalcSum, EmLength, LengthCalc, PixelsAndPercent, ViewportLength } from './input.ts';
export { applyEnvironment } from './environment.ts';
export type { BoxShape } from './paint.ts';
export type { BorderOp, BorderOpKind, DashFaults } from './paint-dash.ts';
export { borderNeedsSidePainter, borderPaintOps, NO_DASH_FAULTS, selectBestDashGap } from './paint-dash.ts';
export type { EnvLength, FontCalc, FontMetricLength, FontPercent, FontSpec, LineHeightCalc, LineHeightLength, RootFontLength, SafeAreaInsets, SafeAreaSide, TextFont, ViewportSize, ViewportUnitSizes } from './input.ts';
export type { EnvironmentDependencies } from './environment.ts';
export { environmentDependencies, resolveEnvironment } from './environment.ts';
export type { FontLengths } from './text.ts';
export { fontMetricLengths } from './text.ts';
// ANIM-b1 (T065): the rt roots the runtime animator's TypeScript reference runs (packages/parity/src/anim-cases.ts), namespaced.
export * as rtEasing from './rt-easing.ts';
export * as rtTiming from './rt-timing.ts';
export * as rtInterpolate from './rt-interpolate.ts';
export * as rtKeyframes from './rt-keyframes.ts';
export * as rtTransition from './rt-transition.ts';
export * as rtAnimations from './rt-animations.ts';
// ANIM-b1 3b (T065 R16): the runtime animator, one implementation for the TypeScript reference and the generated runtimes.
export * as rtAnimator from './rt-animator.ts';
export type { AnimTables, EasingCode, EntryCode, ValueCode } from './rt-animator.ts';
export type { OriginPoint, TransformOrigin } from './paint-transform.ts';
export { mapPoint, paintTransformMatrix, resolveTransformOrigin, transformAboutPoint, transformFunctionsMatrix } from './paint-transform.ts';
export type { LengthValue as TransformLength, Matrix2D, TransformFn, TransformOp, Trig } from './rt-interpolate.ts';
export { serializeTransform } from './rt-interpolate.ts';
// Form controls (FORM-a): the range thumb offset and default track length, and the button's block centring shift.
export { buttonContentShift, controlAsBox, SLIDER_DEFAULT_TRACK_LENGTH, sliderIntrinsicInlineSize, sliderThumbInlineOffset, sliderThumbShift, zoomTrackLength } from './controls.ts';
