// Line break opportunities (docs/decisions.md, "Text strategy"): native text engines give glyph advances only; Dragon decides
// where lines may break. This is Blink's LazyLineBreakIterator (third_party/blink/renderer/platform/text/text_break_iterator.cc
// at Chrome 145.0.7632.6) over a UAX #14 core that matches ICU 77, the ICU in Chrome 145:
// - spaces (U+0020): never break before one; break after a run of them (BreakSpaceType::kAfterSpaceRun);
// - both code points in U+0021..U+00FF: Blink's fast pair table (LineBreakData in character_property_data_generator.cc):
//   ASCII pairs use Blink's own ASCII table (no break after '/', break after '-' and '?', before '(' '<' '[' '{' after some
//   characters), other pairs use the UAX #14 result for the two code points alone;
// - '-' before an ASCII digit breaks only after an ASCII letter or digit ('ABCD-1234', '2024-01-15', but not ' -5');
// - everything else: UAX #14 over the whole run, with CJ resolved to ID as Chrome's ICU data does (languageRules).
// Soft hyphen (U+00AD) is class BA, so a break follows it; that break shows a hyphen (kind 'soft-hyphen'). NBSP is class GL.
// Pinned data: linebreak-data.ts (Unicode 16.0.0, generated by scripts/gen-linebreak-data.ts).
import {
  EAST_ASIAN_ENDS, EAST_ASIAN_STARTS, EXT_PICT_UNASSIGNED_ENDS, EXT_PICT_UNASSIGNED_STARTS,
  LB_AI, LB_AK, LB_AL, LB_AP, LB_AS, LB_B2, LB_BA, LB_BB, LB_BK, LB_CB, LB_CJ, LB_CL, LB_CM, LB_CP, LB_CR, LB_EB, LB_EM, LB_EX,
  LB_GL, LB_H2, LB_H3, LB_HL, LB_HY, LB_ID, LB_IN, LB_IS, LB_JL, LB_JT, LB_JV, LB_LF, LB_NL, LB_NS, LB_NU, LB_OP, LB_PO, LB_PR,
  LB_QU, LB_QU_PF, LB_QU_PI, LB_RI, LB_SA, LB_SA_M, LB_SG, LB_SP, LB_STARTS, LB_SY, LB_VALUES, LB_VF, LB_VI, LB_WJ, LB_XX, LB_ZW,
  LB_ZWJ,
} from './linebreak-data.ts';

const SPACE = 0x20;
const HYPHEN_MINUS = 0x2d;
const SOLIDUS = 0x2f;
const SOFT_HYPHEN = 0xad;
const HYPHEN = 0x2010;
const ZWJ = 0x200d;
const DOTTED_CIRCLE = 0x25cc;

/** css-text-4 §3.1 white-space-collapse. Only collapse is supported: the compiler applies white-space phase I first. */
export type WhiteSpaceCollapseValue = 'collapse' | 'discard' | 'preserve' | 'preserve-breaks' | 'preserve-spaces' | 'break-spaces';
/** css-text-4 §3.2 text-wrap-mode. */
export type TextWrapModeValue = 'wrap' | 'nowrap';
/** css-text-3 §5.2 word-break. Only normal is supported. */
export type WordBreakValue = 'normal' | 'break-all' | 'keep-all' | 'break-word' | 'auto-phrase';
/** css-text-3 §5.5 overflow-wrap. Only normal is supported (no emergency breaks inside words). */
export type OverflowWrapValue = 'normal' | 'break-word' | 'anywhere';
/** css-text-3 §5.3 line-break. Only auto is supported. */
export type LineBreakValue = 'auto' | 'loose' | 'normal' | 'strict' | 'anywhere';
/** css-text-3 §6.1 hyphens. Only manual (the initial value: soft hyphens break) is supported. */
export type HyphensValue = 'manual' | 'none' | 'auto';
/**
 * The ICU rules Chrome 145 applies for line-break: auto, which depend only on whether the content language is Chinese. Measured
 * with Chrome's own ICU (Intl.v8BreakIterator, type line) over LineBreakTest-16.0.0: for en, ja, ja-JP, ko, ko-KR, de, fi, sv,
 * he, ar, hi, th and und it equals UAX #14 with class CJ resolved to ID ('cj-ideographic'; Chromium's ICU data applies CSS
 * line-break: normal by default, unlike upstream ICU's root rules, which resolve CJ to NS). For zh, zh-Hant, zh-CN and zh-TW it
 * uses ICU's line_cj tailoring ('chinese'), which is refused.
 */
export type LanguageLineRules = 'cj-ideographic' | 'chinese';

/** Every input that decides the opportunities, explicit: nothing is defaulted. */
export type LineBreakStyle = {
  readonly whiteSpaceCollapse: WhiteSpaceCollapseValue;
  readonly textWrapMode: TextWrapModeValue;
  readonly wordBreak: WordBreakValue;
  readonly overflowWrap: OverflowWrapValue;
  readonly lineBreak: LineBreakValue;
  readonly hyphens: HyphensValue;
  readonly languageRules: LanguageLineRules;
};

/** 'soft-hyphen': the break follows U+00AD, and the line that ends there shows a hyphen glyph. */
export type BreakKind = 'normal' | 'soft-hyphen';

/** A break opportunity before code point `position`: the next line would start there (after any spaces that hang). */
export type BreakOpportunity = { readonly position: number; readonly kind: BreakKind };

export type LineBreakResult =
  | { readonly ok: true; readonly opportunities: readonly BreakOpportunity[] }
  | { readonly ok: false; readonly reason: string };

/** Planted faults for the oracle tests; each moves one Blink rule to the ICU (or native) behaviour. */
export type LineBreakFaults = {
  /** Allow a break after '/' before a letter or digit, as ICU does (Blink's ASCII table forbids it). */
  readonly breakAfterSolidus: boolean;
  /** Forbid a break between '-' and a digit, as UAX #14 LB25 does (Blink allows it after a letter or digit). */
  readonly noHyphenDigitBreak: boolean;
};

export const NO_LINE_BREAK_FAULTS: LineBreakFaults = { breakAfterSolidus: false, noHyphenDigitBreak: false };

// ---------------------------------------------------------------------------------------------------------------------------
// Data lookup

/** The index of the last start at or before cp (starts[0] is 0), by a power-of-two search, which needs no rounding. */
function rangeIndex(starts: readonly number[], cp: number): number {
  let step = 1;
  while (step * 2 <= starts.length) step = step * 2;
  let pos = 0;
  while (step >= 1) {
    if (pos + step < starts.length && (starts[pos + step] as number) <= cp) pos = pos + step;
    step = step / 2;
  }
  return pos;
}

/** The Line_Break class code of cp (linebreak-data.ts codes, before LB1 resolution). */
export function lineBreakClass(cp: number): number {
  return LB_VALUES[rangeIndex(LB_STARTS, cp)] as number;
}

function inRanges(starts: readonly number[], ends: readonly number[], cp: number): boolean {
  if (starts.length === 0 || cp < (starts[0] as number)) return false;
  return cp <= (ends[rangeIndex(starts, cp)] as number);
}

/** $EastAsian: East_Asian_Width F, W or H. */
export function isEastAsian(cp: number): boolean {
  return inRanges(EAST_ASIAN_STARTS, EAST_ASIAN_ENDS, cp);
}

function isExtPictUnassigned(cp: number): boolean {
  return inRanges(EXT_PICT_UNASSIGNED_STARTS, EXT_PICT_UNASSIGNED_ENDS, cp);
}

// ---------------------------------------------------------------------------------------------------------------------------
// UAX #14 (revision 53, Unicode 16.0.0) core

/** LB1: AI, SG, XX and SA without Mn/Mc resolve to AL, SA with Mn/Mc to CM, CJ to NS (strict) or ID (normal). */
function resolveClass(c: number, cjIsIdeographic: boolean): number {
  if (c === LB_AI || c === LB_SG || c === LB_XX || c === LB_SA) return LB_AL;
  if (c === LB_SA_M) return LB_CM;
  if (c === LB_CJ) return cjIsIdeographic ? LB_ID : LB_NS;
  return c;
}

function isQu(c: number): boolean {
  return c === LB_QU || c === LB_QU_PI || c === LB_QU_PF;
}

/** The text after LB9 and LB10: one unit per combining sequence, carrying its base code point's class and properties. */
type Units = {
  readonly cls: readonly number[];
  readonly cp: readonly number[];
  readonly wide: readonly boolean[];
  readonly start: readonly number[];
};

function unitsOf(text: readonly number[], cjIsIdeographic: boolean): Units {
  const cls: number[] = [];
  const cp: number[] = [];
  const wide: boolean[] = [];
  const start: number[] = [];
  for (let i = 0; i < text.length; i++) {
    const ch = text[i] as number;
    const c = resolveClass(lineBreakClass(ch), cjIsIdeographic);
    if (c === LB_CM || c === LB_ZWJ) {
      const n = cls.length;
      const base = n > 0 ? (cls[n - 1] as number) : LB_SP;
      // LB9: X (CM | ZWJ)* is X, for X not BK, CR, LF, NL, SP or ZW.
      if (n > 0 && base !== LB_BK && base !== LB_CR && base !== LB_LF && base !== LB_NL && base !== LB_SP && base !== LB_ZW) continue;
      // LB10: any remaining CM or ZWJ is AL.
      cls.push(LB_AL);
    } else {
      cls.push(c);
    }
    cp.push(ch);
    wide.push(isEastAsian(ch));
    start.push(i);
  }
  return { cls, cp, wide, start };
}

function clsAt(u: Units, k: number): number {
  return k >= 0 && k < u.cls.length ? (u.cls[k] as number) : -1;
}

/** Index of the first unit before k that is not SP (-1 when there is none). */
function skipSpacesBack(u: Units, k: number): number {
  let j = k;
  while (j >= 0 && (u.cls[j] as number) === LB_SP) j--;
  return j;
}

function isAkDottedAs(u: Units, k: number): boolean {
  const c = clsAt(u, k);
  return c === LB_AK || c === LB_AS || (k >= 0 && k < u.cp.length && (u.cp[k] as number) === DOTTED_CIRCLE);
}

/** Whether UAX #14 allows a break before unit k (k >= 1), given the raw text for LB8a. */
function unitBreak(u: Units, k: number, text: readonly number[]): boolean {
  const p = clsAt(u, k - 1);
  const c = clsAt(u, k);
  const n = clsAt(u, k + 1);
  // LB4, LB5
  if (p === LB_BK) return true;
  if (p === LB_CR && c === LB_LF) return false;
  if (p === LB_CR || p === LB_LF || p === LB_NL) return true;
  // LB6, LB7
  if (c === LB_BK || c === LB_CR || c === LB_LF || c === LB_NL) return false;
  if (c === LB_SP || c === LB_ZW) return false;
  // LB8: ZW SP* ÷
  const beforeSpaces = skipSpacesBack(u, k - 1);
  if (clsAt(u, beforeSpaces) === LB_ZW) return true;
  // LB8a: ZWJ ×
  if ((text[(u.start[k] as number) - 1] as number) === ZWJ) return false;
  // LB11
  if (c === LB_WJ || p === LB_WJ) return false;
  // LB12, LB12a
  if (p === LB_GL) return false;
  if (c === LB_GL && p !== LB_SP && p !== LB_BA && p !== LB_HY) return false;
  // LB13
  if (c === LB_CL || c === LB_CP || c === LB_EX || c === LB_SY) return false;
  // LB14: OP SP* ×
  if (clsAt(u, beforeSpaces) === LB_OP) return false;
  // LB15a: (sot | BK | CR | LF | NL | OP | QU | GL | SP | ZW) [\p{Pi}&QU] SP* ×
  if (clsAt(u, beforeSpaces) === LB_QU_PI) {
    const b = clsAt(u, beforeSpaces - 1);
    if (beforeSpaces === 0 || b === LB_BK || b === LB_CR || b === LB_LF || b === LB_NL || b === LB_OP || isQu(b) || b === LB_GL || b === LB_SP || b === LB_ZW) return false;
  }
  // LB15b: × [\p{Pf}&QU] ( SP | GL | WJ | CL | QU | CP | EX | IS | SY | BK | CR | LF | NL | ZW | eot)
  if (c === LB_QU_PF) {
    if (k + 1 >= u.cls.length) return false;
    if (n === LB_SP || n === LB_GL || n === LB_WJ || n === LB_CL || isQu(n) || n === LB_CP || n === LB_EX || n === LB_IS || n === LB_SY || n === LB_BK || n === LB_CR || n === LB_LF || n === LB_NL || n === LB_ZW) return false;
  }
  // LB15c: SP ÷ IS NU; LB15d: × IS
  if (p === LB_SP && c === LB_IS && n === LB_NU) return true;
  if (c === LB_IS) return false;
  // LB16: (CL | CP) SP* × NS
  if (c === LB_NS && (clsAt(u, beforeSpaces) === LB_CL || clsAt(u, beforeSpaces) === LB_CP)) return false;
  // LB17: B2 SP* × B2
  if (c === LB_B2 && clsAt(u, beforeSpaces) === LB_B2) return false;
  // LB18
  if (p === LB_SP) return true;
  // LB19: × [QU - \p{Pi}]; [QU - \p{Pf}] ×
  if (c === LB_QU || c === LB_QU_PF) return false;
  if (p === LB_QU || p === LB_QU_PI) return false;
  // LB19a: unless surrounded by East Asian characters, do not break either side of any quotation mark.
  if (isQu(c)) {
    if (!(u.wide[k - 1] as boolean)) return false;
    if (k + 1 >= u.cls.length || !(u.wide[k + 1] as boolean)) return false;
  }
  if (isQu(p)) {
    if (!(u.wide[k] as boolean)) return false;
    if (k - 2 < 0 || !(u.wide[k - 2] as boolean)) return false;
  }
  // LB20
  if (c === LB_CB || p === LB_CB) return true;
  // LB20a: (sot | BK | CR | LF | NL | SP | ZW | CB | GL) (HY | U+2010) × AL
  if ((p === LB_HY || (u.cp[k - 1] as number) === HYPHEN) && c === LB_AL) {
    const b = clsAt(u, k - 2);
    if (k - 2 < 0 || b === LB_BK || b === LB_CR || b === LB_LF || b === LB_NL || b === LB_SP || b === LB_ZW || b === LB_CB || b === LB_GL) return false;
  }
  // LB21
  if (c === LB_BA || c === LB_HY || c === LB_NS || p === LB_BB) return false;
  // LB21a: HL (HY | [BA - $EastAsian]) × [^HL]
  if ((p === LB_HY || (p === LB_BA && !(u.wide[k - 1] as boolean))) && clsAt(u, k - 2) === LB_HL && c !== LB_HL) return false;
  // LB21b
  if (p === LB_SY && c === LB_HL) return false;
  // LB22
  if (c === LB_IN) return false;
  // LB23
  if ((p === LB_AL || p === LB_HL) && c === LB_NU) return false;
  if (p === LB_NU && (c === LB_AL || c === LB_HL)) return false;
  // LB23a
  if (p === LB_PR && (c === LB_ID || c === LB_EB || c === LB_EM)) return false;
  if ((p === LB_ID || p === LB_EB || p === LB_EM) && c === LB_PO) return false;
  // LB24
  if ((p === LB_PR || p === LB_PO) && (c === LB_AL || c === LB_HL)) return false;
  if ((p === LB_AL || p === LB_HL) && (c === LB_PR || c === LB_PO)) return false;
  // LB25
  if (c === LB_PO || c === LB_PR) {
    let j = k - 1;
    if (clsAt(u, j) === LB_CL || clsAt(u, j) === LB_CP) j--;
    while (clsAt(u, j) === LB_SY || clsAt(u, j) === LB_IS) j--;
    if (clsAt(u, j) === LB_NU) return false;
  }
  if (p === LB_PO || p === LB_PR) {
    if (c === LB_NU) return false;
    if (c === LB_OP && n === LB_NU) return false;
    if (c === LB_OP && n === LB_IS && clsAt(u, k + 2) === LB_NU) return false;
  }
  if ((p === LB_HY || p === LB_IS) && c === LB_NU) return false;
  if (c === LB_NU) {
    let j = k - 1;
    while (clsAt(u, j) === LB_SY || clsAt(u, j) === LB_IS) j--;
    if (clsAt(u, j) === LB_NU) return false;
  }
  // LB26
  if (p === LB_JL && (c === LB_JL || c === LB_JV || c === LB_H2 || c === LB_H3)) return false;
  if ((p === LB_JV || p === LB_H2) && (c === LB_JV || c === LB_JT)) return false;
  if ((p === LB_JT || p === LB_H3) && c === LB_JT) return false;
  // LB27
  if ((p === LB_JL || p === LB_JV || p === LB_JT || p === LB_H2 || p === LB_H3) && c === LB_PO) return false;
  if (p === LB_PR && (c === LB_JL || c === LB_JV || c === LB_JT || c === LB_H2 || c === LB_H3)) return false;
  // LB28
  if ((p === LB_AL || p === LB_HL) && (c === LB_AL || c === LB_HL)) return false;
  // LB28a
  if (p === LB_AP && isAkDottedAs(u, k)) return false;
  if (isAkDottedAs(u, k - 1) && (c === LB_VF || c === LB_VI)) return false;
  if (p === LB_VI && isAkDottedAs(u, k - 2) && (c === LB_AK || (u.cp[k] as number) === DOTTED_CIRCLE)) return false;
  if (isAkDottedAs(u, k - 1) && isAkDottedAs(u, k) && n === LB_VF) return false;
  // LB29
  if (p === LB_IS && (c === LB_AL || c === LB_HL)) return false;
  // LB30
  if ((p === LB_AL || p === LB_HL || p === LB_NU) && c === LB_OP && !(u.wide[k] as boolean)) return false;
  if (p === LB_CP && !(u.wide[k - 1] as boolean) && (c === LB_AL || c === LB_HL || c === LB_NU)) return false;
  // LB30a: an odd number of RI before
  if (p === LB_RI && c === LB_RI) {
    let odd = false;
    let j = k - 1;
    while (clsAt(u, j) === LB_RI) {
      odd = !odd;
      j--;
    }
    if (odd) return false;
  }
  // LB30b
  if (c === LB_EM && (p === LB_EB || isExtPictUnassigned(u.cp[k - 1] as number))) return false;
  // LB31
  return true;
}

/**
 * UAX #14 break permission at every boundary of text: result[i] is the boundary before text[i], result[0] is start of text
 * (never) and result[text.length] is end of text (always). Mandatory breaks count as allowed. cjIsIdeographic selects LB1's
 * CSS line-break: normal resolution of CJ to ID (Chrome's ICU) instead of the UAX #14 default, NS.
 */
export function uax14BreakAllowed(text: readonly number[], cjIsIdeographic: boolean): readonly boolean[] {
  const u = unitsOf(text, cjIsIdeographic);
  const out: boolean[] = [];
  let k = 0;
  for (let i = 0; i <= text.length; i++) {
    if (i === text.length) {
      out.push(i > 0);
    } else if (k < u.start.length && (u.start[k] as number) === i) {
      // Boundaries inside a unit (before an attached CM or ZWJ) are LB9's ×.
      out.push(k > 0 && unitBreak(u, k, text));
      k++;
    } else {
      out.push(false);
    }
  }
  return out;
}

// ---------------------------------------------------------------------------------------------------------------------------
// Blink's fast pair table (U+0021..U+00FF)

/**
 * LineBreakData::FillAscii (third_party/blink/renderer/platform/text/character_property_data_generator.cc 433-470 at
 * 145.0.7632.6, BSD), in order: [firstMin, firstMax, secondMin, secondMax, breaks]. A later entry overrides an earlier one,
 * so the lookup scans from the end.
 */
const ASCII_PAIR_OPS: readonly (readonly number[])[] = [
  [0x21, 0x7f, 0x21, 0x7f, 0],
  [0x21, 0x7f, 0x28, 0x28, 1], // before '('
  [0x21, 0x7f, 0x3c, 0x3c, 1], // before '<'
  [0x21, 0x7f, 0x5b, 0x5b, 1], // before '['
  [0x21, 0x7f, 0x7b, 0x7b, 1], // before '{'
  [0x2d, 0x2d, 0x21, 0x7f, 1], // after '-'
  [0x3f, 0x3f, 0x21, 0x7f, 1], // after '?'
  [0x2d, 0x2d, 0x24, 0x24, 0], // '-' '$'
  [0x21, 0x7f, 0x21, 0x21, 0], // before '!'
  [0x3f, 0x3f, 0x22, 0x22, 0], // '?' '"'
  [0x3f, 0x3f, 0x27, 0x27, 0], // '?' '\''
  [0x21, 0x7f, 0x29, 0x29, 0], // before ')'
  [0x21, 0x7f, 0x2c, 0x2c, 0], // before ','
  [0x21, 0x7f, 0x2e, 0x2e, 0], // before '.'
  [0x21, 0x7f, 0x2f, 0x2f, 0], // before '/'
  [0x2d, 0x2d, 0x30, 0x39, 0], // '-' digit (decided by the hyphen-digit rule before the table)
  [0x21, 0x7f, 0x3a, 0x3a, 0], // before ':'
  [0x21, 0x7f, 0x3b, 0x3b, 0], // before ';'
  [0x21, 0x7f, 0x3f, 0x3f, 0], // before '?'
  [0x21, 0x7f, 0x5d, 0x5d, 0], // before ']'
  [0x21, 0x7f, 0x7d, 0x7d, 0], // before '}'
  [0x24, 0x24, 0x21, 0x7f, 0], // after '$'
  [0x27, 0x27, 0x21, 0x7f, 0], // after '\''
  [0x28, 0x28, 0x21, 0x7f, 0], // after '('
  [0x2f, 0x2f, 0x21, 0x7f, 0], // after '/'
  [0x30, 0x39, 0x21, 0x7f, 0], // after a digit
  [0x3c, 0x3c, 0x21, 0x7f, 0], // after '<'
  [0x40, 0x40, 0x21, 0x7f, 0], // after '@'
  [0x41, 0x5a, 0x21, 0x7f, 0], // after 'A'-'Z'
  [0x5b, 0x5b, 0x21, 0x7f, 0], // after '['
  [0x5e, 0x60, 0x21, 0x7f, 0], // after '^' '_' '`'
  [0x61, 0x7a, 0x21, 0x7f, 0], // after 'a'-'z'
  [0x7b, 0x7b, 0x21, 0x7f, 0], // after '{'
  [0x7f, 0x7f, 0x21, 0x7f, 0], // after DEL
];

function asciiPairBreaks(a: number, b: number): boolean {
  for (let k = ASCII_PAIR_OPS.length - 1; k >= 0; k--) {
    const op = ASCII_PAIR_OPS[k] as readonly number[];
    if (a >= (op[0] as number) && a <= (op[1] as number) && b >= (op[2] as number) && b <= (op[3] as number)) return (op[4] as number) === 1;
  }
  return false;
}

function isAsciiDigit(cp: number): boolean {
  return cp >= 0x30 && cp <= 0x39;
}

function isAsciiAlphanumeric(cp: number): boolean {
  return isAsciiDigit(cp) || (cp >= 0x41 && cp <= 0x5a) || (cp >= 0x61 && cp <= 0x7a);
}

const FAST_NO = 0;
const FAST_YES = 1;
const FAST_UNKNOWN = 2;

function fastBreak(lastLast: number, last: number, cur: number, faults: LineBreakFaults): number {
  throw new Error('T123 clean-room: not implemented');
}

// ---------------------------------------------------------------------------------------------------------------------------
// Opportunities

/** A reason the text or style is outside what this module decides, or null. */
function refusal(text: readonly number[], style: LineBreakStyle): string | null {
  if (style.whiteSpaceCollapse !== 'collapse') return `white-space-collapse: ${style.whiteSpaceCollapse} is not supported (only collapse)`;
  if (style.wordBreak !== 'normal') return `word-break: ${style.wordBreak} is not supported (only normal)`;
  if (style.overflowWrap !== 'normal') return `overflow-wrap: ${style.overflowWrap} is not supported (only normal)`;
  if (style.lineBreak !== 'auto') return `line-break: ${style.lineBreak} is not supported (only auto)`;
  if (style.hyphens !== 'manual') return `hyphens: ${style.hyphens} is not supported (only manual)`;
  if (style.languageRules !== 'cj-ideographic') return 'Chinese content languages use ICU line_cj rules, which are not supported';
  for (let i = 0; i < text.length; i++) {
    const cp = text[i] as number;
    const at = `U+${cp.toString(16).toUpperCase()} at ${i}`;
    if ((cp < 0x20 || (cp >= 0x7f && cp <= 0x9f))) return `${at} is a control character; collapsed text has none`;
    const c = lineBreakClass(cp);
    if (c === LB_BK || c === LB_CR || c === LB_LF || c === LB_NL) return `${at} is a forced line break, which is not supported`;
    if (c === LB_SA || c === LB_SA_M) return `${at} needs dictionary-based line breaking (UAX #14 class SA), which is not supported`;
    if (c === LB_SG) return `${at} is a lone surrogate`;
    // Space separators other than U+0020, U+3000 and the no-break spaces: whether they hang at a line end is not measured.
    if (cp === 0x1680 || (cp >= 0x2000 && cp <= 0x200a) || cp === 0x205f) return `${at} is a space separator whose line-end behaviour is not measured`;
  }
  return null;
}

function isBreakableSpace(cp: number): boolean {
  throw new Error('T123 clean-room: not implemented');
}

export function lineBreakOpportunitiesWith(text: readonly number[], style: LineBreakStyle, faults: LineBreakFaults): LineBreakResult {
  throw new Error('T123 clean-room: not implemented');
}

/** The break opportunities of one run of text (code points), in order. */
export function lineBreakOpportunities(text: readonly number[], style: LineBreakStyle): LineBreakResult {
  return lineBreakOpportunitiesWith(text, style, NO_LINE_BREAK_FAULTS);
}
