// Captures Chrome's computed values for html, body, div and an element with no UA rules, for every milestone longhand,
// and which longhands a UA rule sets per tag: those whose value differs from the same element with "<longhand>: initial".
// Blink's html.css is LGPL, so Dragon stores these captured values as data instead of copying the sheet.
// The dataset is keyed by the capture platform (process.platform-process.arch): it writes only this platform's file,
// packages/dragon/src/ua/chrome-145.<platform>.generated.ts, and refuses a platform argument other than this one.
// Run with: pnpm run ua:capture [platform]
import { writeFileSync } from 'node:fs';
import { CHROME_VERSION, launchChrome, openPage } from '../packages/parity/src/chrome.ts';
import { repoPath } from '../packages/parity/src/paths.ts';
import { hostPlatform } from '../packages/parity/src/platform.ts';
import { LONGHANDS } from '../packages/dragon/src/css/properties.ts';

const TAGS = ['html', 'body', 'div', 'dragon-unstyled'] as const;
const BORDER_KEYWORDS = ['thin', 'medium', 'thick'] as const;

// Width, height, margins and padding resolve to used values on rendered elements (CSSOM getComputedStyle),
// so every element except html's own display is read from a document whose root is display:none.
const hiddenDoc = `<!DOCTYPE html><html><head><style>html{display:none}</style></head><body><div></div><dragon-unstyled></dragon-unstyled>${BORDER_KEYWORDS.map((k) => `<dragon-unstyled data-border="${k}" style="border-style:solid;border-width:${k}"></dragon-unstyled>`).join('')}</body></html>`;
const renderedDoc = '<!DOCTYPE html><html><head></head><body></body></html>';

const platform = hostPlatform();
const requested = process.argv[2];
if (requested !== undefined && requested !== platform) {
  console.error(`ua:capture refuses to write the ${requested} dataset on ${platform}: a dataset is captured only on its own platform`);
  process.exit(1);
}
// The UA capture reads Chrome's own root font, so the harness adds no environment font.
const ENV = { viewport: { width: 400, height: 300 }, devicePixelRatio: 1, direction: 'ltr', rootFont: 'ua-default' } as const;
const browser = await launchChrome();
try {
  const hidden = await openPage(browser, hiddenDoc, ENV);
  const { out: values, initial } = await hidden.evaluate(
    ({ tags, props }) => {
      const out: Record<string, Record<string, string>> = {};
      const initial: Record<string, Record<string, string>> = {};
      for (const tag of tags) {
        const el = document.querySelector(tag === 'dragon-unstyled' ? 'dragon-unstyled:not([data-border])' : tag) as HTMLElement;
        const cs = getComputedStyle(el);
        out[tag] = Object.fromEntries(props.map((p) => [p, cs.getPropertyValue(p)]));
        initial[tag] = Object.fromEntries(props.map((p) => {
          el.style.setProperty(p, 'initial');
          const v = getComputedStyle(el).getPropertyValue(p);
          el.style.removeProperty(p);
          return [p, v];
        }));
      }
      return { out, initial };
    },
    { tags: [...TAGS], props: [...LONGHANDS] },
  );
  const borderKeywords = await hidden.evaluate(() =>
    Object.fromEntries(
      Array.from(document.querySelectorAll('[data-border]')).map((e) => [e.getAttribute('data-border'), getComputedStyle(e).borderTopWidth]),
    ),
  );
  const rendered = await openPage(browser, renderedDoc, ENV);
  const htmlDisplay = await rendered.evaluate(() => {
    const el = document.documentElement;
    const own = getComputedStyle(el).display;
    el.style.setProperty('display', 'initial');
    const init = getComputedStyle(el).display;
    el.style.removeProperty('display');
    return { own, init };
  });
  (values['html'] as Record<string, string>)['display'] = htmlDisplay.own;
  (initial['html'] as Record<string, string>)['display'] = htmlDisplay.init;

  const lines: string[] = [];
  lines.push(`// Generated by scripts/capture-ua-defaults.ts from Chrome ${CHROME_VERSION} computed values. Do not edit; run pnpm run ua:capture.`);
  lines.push('');
  lines.push(`export const chromeVersion = ${JSON.stringify(CHROME_VERSION)};`);
  lines.push('');
  lines.push('/** The capture platform (process.platform-process.arch) this dataset was read on. */');
  lines.push(`export const platform = ${JSON.stringify(platform)};`);
  lines.push('');
  lines.push('export type CapturedTag = ' + TAGS.map((t) => JSON.stringify(t)).join(' | ') + ';');
  lines.push('');
  lines.push('export const computed: { readonly [T in CapturedTag]: { readonly [property: string]: string } } = {');
  for (const tag of TAGS) {
    lines.push(`  ${JSON.stringify(tag)}: {`);
    const row = values[tag] as Record<string, string>;
    for (const p of [...LONGHANDS].sort()) lines.push(`    ${JSON.stringify(p)}: ${JSON.stringify(row[p])},`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('/** Longhands a Chrome UA rule sets per tag: the captured value differs from the value under "<longhand>: initial". */');
  lines.push('export const userAgentLonghands: { readonly [T in CapturedTag]: readonly string[] } = {');
  for (const tag of TAGS) {
    const own = values[tag] as Record<string, string>;
    const init = initial[tag] as Record<string, string>;
    const set = [...LONGHANDS].sort().filter((p) => own[p] !== init[p]);
    lines.push(`  ${JSON.stringify(tag)}: ${JSON.stringify(set)},`);
  }
  lines.push('};');
  lines.push('');
  lines.push('/** Computed border widths for the line-width keywords, read with border-style: solid. */');
  lines.push('export const borderWidthKeywords: { readonly [keyword: string]: string } = {');
  for (const k of BORDER_KEYWORDS) lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(borderKeywords[k])},`);
  lines.push('};');
  lines.push('');
  const file = `packages/dragon/src/ua/chrome-145.${platform}.generated.ts`;
  writeFileSync(repoPath(file), lines.join('\n'));
  console.log(`wrote ${file}`);
} finally {
  await browser.close();
}
