// Captures, in the pinned Chrome 145, which property names Chrome parses at all. A name Chrome does not know makes every
// declaration of it invalid, so a @supports (name: value) test is false whatever the value (css-conditional-3 §6.1). Each name is
// read three ways, and the capture refuses to write if they ever disagree: CSS.supports(name, 'initial') (a CSS-wide keyword is
// valid for every property Chrome knows), style.setProperty(name, 'initial') on a probe element, and a style attribute
// "name: initial" read back through the element's cssText. The corpus is every property css-tree's grammar names, each with the
// -webkit- and -moz- prefixes, every property Chrome's CSSStyleDeclaration exposes, and the names Tailwind 4.3.3's @supports
// conditions test. Output: packages/dragon/src/css/property-names.generated.ts. Run with:
//   node --conditions=dragon-internal scripts/capture-property-names.ts [--check]
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { CHROME_VERSION, launchChrome, openPage } from '../packages/parity/src/chrome.ts';
import { repoPath } from '../packages/parity/src/paths.ts';

// css-tree is resolved from packages/dragon, which depends on it.
const { lexer } = createRequire(repoPath('packages/dragon/package.json'))('css-tree') as { lexer: { properties: Record<string, unknown> } };

const OUTPUT = 'packages/dragon/src/css/property-names.generated.ts';

/** Tailwind 4.3.3's @property fallback condition (tailwind-sweep/src/flatten.ts FALLBACK_CONDITION) tests these names. */
const TAILWIND_CORPUS = ['-webkit-hyphens', 'margin-trim', '-moz-orient', 'color'];

async function capture(): Promise<string> {
  const grammar = Object.keys(lexer.properties).filter((n) => !n.startsWith('-'));
  const browser = await launchChrome();
  try {
    if (browser.version() !== CHROME_VERSION) throw new Error(`Chrome ${browser.version()}`);
    const page = await openPage(browser, '<!DOCTYPE html><html><head></head><body><div id="t"></div></body></html>', { viewport: { width: 400, height: 300 }, devicePixelRatio: 1, direction: 'ltr', rootFont: 'ua-default' });
    const result = await page.evaluate(({ grammar, tailwind }) => {
      const el = document.getElementById('t') as HTMLElement;
      // Chrome's CSSStyleDeclaration names every property it implements, as camelCase (webkitX for -webkit-x).
      const own = Object.keys(Object.getPrototypeOf(el.style) as object).concat(Object.keys(el.style))
        .filter((k) => /^[a-zA-Z]+$/.test(k) && typeof (el.style as unknown as Record<string, unknown>)[k] === 'string')
        .map((k) => k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`).replace(/^(webkit|moz|epub)-/, '-$1-'));
      const names = [...new Set([...grammar, ...grammar.flatMap((n) => [`-webkit-${n}`, `-moz-${n}`]), ...own, ...tailwind])].sort();
      const out: Record<string, { supports: boolean; set: boolean; attr: boolean }> = {};
      for (const name of names) {
        el.removeAttribute('style');
        el.style.setProperty(name, 'initial');
        const set = el.style.getPropertyValue(name) !== '' || el.style.length > 0;
        el.setAttribute('style', `${name}: initial`);
        const attr = el.style.cssText !== '';
        out[name] = { supports: CSS.supports(name, 'initial'), set, attr };
      }
      el.removeAttribute('style');
      return out;
    }, { grammar, tailwind: TAILWIND_CORPUS });
    for (const [name, r] of Object.entries(result)) {
      if (r.supports !== r.set || r.supports !== r.attr) throw new Error(`Chrome's knowledge of ${name} is not observable exactly: CSS.supports ${r.supports}, setProperty ${r.set}, style attribute ${r.attr}`);
    }
    const list = (known: boolean): string => Object.keys(result).filter((n) => (result[n] as { supports: boolean }).supports === known).sort().map((n) => `  '${n}',`).join('\n');
    return `// Generated by scripts/capture-property-names.ts in Chrome ${CHROME_VERSION}; do not edit. Whether Chrome parses a property name at all,
// read three ways that agree for every name: CSS.supports(name, 'initial'), style.setProperty, and a style attribute. A name in
// neither list was not probed, so Dragon cannot say whether Chrome knows it.

export const PROPERTY_NAMES_CHROME = '${CHROME_VERSION}';

/** Property names Chrome 145 parses. */
export const CHROME_KNOWN_PROPERTIES: readonly string[] = [
${list(true)}
];

/** Property names Chrome 145 does not parse: every declaration of one is invalid. */
export const CHROME_UNKNOWN_PROPERTIES: readonly string[] = [
${list(false)}
];
`;
  } finally {
    await browser.close();
  }
}

const text = await capture();
if (process.argv.includes('--check')) {
  const committed = readFileSync(repoPath(OUTPUT), 'utf8');
  if (committed !== text) {
    console.error(`${OUTPUT} differs from a fresh capture`);
    process.exit(1);
  }
  console.log(`${OUTPUT} matches a fresh capture`);
} else {
  writeFileSync(repoPath(OUTPUT), text);
  console.log(`wrote ${OUTPUT}`);
}
