// Captures Chrome's computed values for html, body, div and an element with no UA rules, for every milestone longhand.
// Blink's html.css is LGPL, so Dragon stores these captured values as data instead of copying the sheet.
// Run with: pnpm run ua:capture
import { writeFileSync } from 'node:fs';
import { CHROME_VERSION, launchChrome, openPage } from '../packages/parity/src/chrome.ts';
import { repoPath } from '../packages/parity/src/paths.ts';
import { LONGHANDS } from '../packages/dragon/src/css/properties.ts';

const TAGS = ['html', 'body', 'div', 'dragon-unstyled'] as const;
const BORDER_KEYWORDS = ['thin', 'medium', 'thick'] as const;

// Width, height, margins and padding resolve to used values on rendered elements (CSSOM getComputedStyle),
// so every element except html's own display is read from a document whose root is display:none.
const hiddenDoc = `<!DOCTYPE html><html><head><style>html{display:none}</style></head><body><div></div><dragon-unstyled></dragon-unstyled>${BORDER_KEYWORDS.map((k) => `<dragon-unstyled data-border="${k}" style="border-style:solid;border-width:${k}"></dragon-unstyled>`).join('')}</body></html>`;
const renderedDoc = '<!DOCTYPE html><html><head></head><body></body></html>';

const browser = await launchChrome();
try {
  const hidden = await openPage(browser, hiddenDoc, { width: 400, height: 300 });
  const values = await hidden.evaluate(
    ({ tags, props }) => {
      const out: Record<string, Record<string, string>> = {};
      for (const tag of tags) {
        const el = document.querySelector(tag === 'dragon-unstyled' ? 'dragon-unstyled:not([data-border])' : tag) as Element;
        const cs = getComputedStyle(el);
        out[tag] = Object.fromEntries(props.map((p) => [p, cs.getPropertyValue(p)]));
      }
      return out;
    },
    { tags: [...TAGS], props: [...LONGHANDS] },
  );
  const borderKeywords = await hidden.evaluate(() =>
    Object.fromEntries(
      Array.from(document.querySelectorAll('[data-border]')).map((e) => [e.getAttribute('data-border'), getComputedStyle(e).borderTopWidth]),
    ),
  );
  const rendered = await openPage(browser, renderedDoc, { width: 400, height: 300 });
  const htmlDisplay = await rendered.evaluate(() => getComputedStyle(document.documentElement).display);
  (values['html'] as Record<string, string>)['display'] = htmlDisplay;

  const lines: string[] = [];
  lines.push(`// Generated by scripts/capture-ua-defaults.ts from Chrome ${CHROME_VERSION} computed values. Do not edit; run pnpm run ua:capture.`);
  lines.push('');
  lines.push(`export const chromeVersion = ${JSON.stringify(CHROME_VERSION)};`);
  lines.push('');
  lines.push('export type CapturedTag = ' + TAGS.map((t) => JSON.stringify(t)).join(' | ') + ';');
  lines.push('');
  lines.push('export const computed: { readonly [T in CapturedTag]: { readonly [property: string]: string } } = {');
  for (const tag of TAGS) {
    lines.push(`  ${JSON.stringify(tag)}: {`);
    const row = values[tag] as Record<string, string>;
    for (const p of [...LONGHANDS].sort()) lines.push(`    ${JSON.stringify(p)}: ${JSON.stringify(row[p])},`);
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push('/** Computed border widths for the line-width keywords, read with border-style: solid. */');
  lines.push('export const borderWidthKeywords: { readonly [keyword: string]: string } = {');
  for (const k of BORDER_KEYWORDS) lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(borderKeywords[k])},`);
  lines.push('};');
  lines.push('');
  writeFileSync(repoPath('packages/dragon/src/ua/chrome-145.generated.ts'), lines.join('\n'));
  console.log('wrote packages/dragon/src/ua/chrome-145.generated.ts');
} finally {
  await browser.close();
}
