// Proves the FORM-a A2 (T052J) appearance migration of committed outputs is additive only (docs/decisions.md, "Adding engine
// fields and CSS longhands"; route 2a, as object-fit): every file that existed at the base commit either is unchanged or differs
// only by the new longhand, at its initial value (none) or its UA value (auto, on the form-control keys), and no file is added.
// - Chrome captures (packages/parity/expected/**, expected-dpr/**, expected-fonts/**): the computed values of every element node gain
//   "appearance": "none" right after object-position; with it removed the file is byte-identical to the base.
// - Emitted CSS (packages/parity/emitted/**, expected-fonts/emitted/**): every rule gains "appearance: none;" after object-position;
//   with it removed the file is byte-identical to the base, except the header's compilation digest.
// - The UA datasets (packages/dragon/src/ua/*.generated.ts): every computed row gains appearance (auto on button, input and
//   input[type=range], none elsewhere); appearance moves for those three keys from the unmodelled rows to the declared rows and
//   longhand lists, as auto; the forced rows and everything else are unchanged.
// - The engine inputs (packages/layout/vectors/**, break-vectors/**, paint-vectors/**), Chrome's line breaks (expected-breaks/**) and
//   the Chrome pixel manifests (expected-pixels/**/manifest.json): unchanged, since appearance has no layout aspect.
// `--plant <name>` alters one file in memory before the check, which must then fail (PLANTS below). `--ua-plant` also runs
// `pnpm run ua:capture -- --check --plant drop-unmodelled` and requires it to fail naming button's cursor.
// Run with: node scripts/check-appearance-migration.ts <base-commit> [--plant <name>] [--ua-plant]
import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const base = process.argv[2];
if (base === undefined || base.startsWith('--')) {
  console.error('usage: node scripts/check-appearance-migration.ts <base-commit> [--plant <name>] [--ua-plant]');
  process.exit(2);
}

/** A migration: which committed files it covers, and how to take its additions out of one file's text. */
type Migration = {
  readonly name: string;
  readonly roots: readonly string[];
  readonly extension: string;
  /** The after and before texts with the additions removed, and how many it removed; throws on a non-neutral addition. */
  readonly strip: (after: string, before: string, path: string) => { readonly after: string; readonly before: string; readonly removed: number };
};

/** The element keys whose UA appearance is auto (html.css: button, input); every other row is at the initial value. */
const CONTROL_KEYS: ReadonlySet<string> = new Set(['button', 'input', 'input[type=range]']);

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/** The indent of a JSON file written by JSON.stringify(v, null, indent), from its second line. */
function indentOf(text: string): number {
  const second = text.split('\n')[1] ?? '';
  return second.length - second.trimStart().length;
}

/** The computed values of a captured element node: every longhand, so object-position and box-sizing among them. */
const isComputed = (v: Record<string, unknown>): boolean => typeof v['object-position'] === 'string' && typeof v['box-sizing'] === 'string';

/** Captures: each computed object holds appearance at its initial value right after object-position; it is removed. */
function stripCapture(after: string, before: string, path: string): { after: string; before: string; removed: number } {
  const json = JSON.parse(after) as unknown;
  let removed = 0;
  const walk = (v: unknown, at: string): void => {
    if (Array.isArray(v)) {
      v.forEach((x, i) => walk(x, `${at}[${i}]`));
      return;
    }
    if (!isRecord(v)) return;
    if (isComputed(v)) {
      const keys = Object.keys(v);
      if (keys[keys.indexOf('object-position') + 1] !== 'appearance') throw new Error(`${path} ${at}: appearance does not follow object-position`);
      if (v['appearance'] !== 'none') throw new Error(`${path} ${at}: appearance is ${JSON.stringify(v['appearance'])}, not its initial value`);
      delete v['appearance'];
      removed++;
    }
    for (const [k, x] of Object.entries(v)) walk(x, `${at}.${k}`);
  };
  walk(json, '$');
  return { after: `${JSON.stringify(json, null, indentOf(before))}\n`, before, removed };
}

const HEADER = /^\/\* Generated by Dragon from compilation [0-9a-f]{64}\. Do not edit\. \*\/$/;
const RULE = /^\.dg\d+ \{$/;
const APPEARANCE = '  appearance: none;';

/** Emitted CSS: exactly one appearance declaration per rule, after object-position; the header keeps its form with any digest. */
function stripEmitted(after: string, before: string, path: string): { after: string; before: string; removed: number } {
  const lines = after.split('\n');
  const was = before.split('\n');
  if (!HEADER.test(lines[0] ?? '') || !HEADER.test(was[0] ?? '')) throw new Error(`${path}: the header is not the generated-file header`);
  const rules = lines.filter((l) => RULE.test(l)).length;
  const kept: string[] = [was[0] as string];
  let removed = 0;
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i] as string;
    if (line.includes('appearance')) {
      if (line !== APPEARANCE) throw new Error(`${path}:${i + 1}: "${line.trim()}" is not the neutral declaration`);
      if (!(lines[i - 1] ?? '').startsWith('  object-position: ')) throw new Error(`${path}:${i + 1}: appearance does not follow object-position`);
      removed++;
      continue;
    }
    kept.push(line);
  }
  if (removed !== rules) throw new Error(`${path}: ${removed} appearance declarations in ${rules} rules`);
  return { after: kept.join('\n'), before, removed };
}

/** One appearance entry in a UA dataset line: a computed row line, a longhand list item or a declared or unmodelled row entry. */
const UA_ENTRY = /"appearance"(?:: "([^"]*)")?(?:, ?)?/g;
const SECTION = /^export const (\w+)/;
const ROW = /^ {2}"([^"]+)": /;

type UaEntry = { readonly section: string; readonly key: string; readonly value: string | null; readonly line: number };

/** Every appearance entry of a UA dataset with its section and row key, and the text with every one removed. */
function uaEntries(text: string, path: string): { entries: UaEntry[]; text: string } {
  const entries: UaEntry[] = [];
  let section = '';
  let key = '';
  const out: string[] = [];
  for (const [i, line] of text.split('\n').entries()) {
    section = SECTION.exec(line)?.[1] ?? section;
    key = ROW.exec(line)?.[1] ?? key;
    if (!line.includes('appearance')) {
      out.push(line);
      continue;
    }
    for (const m of line.matchAll(UA_ENTRY)) entries.push({ section, key, value: m[1] ?? null, line: i + 1 });
    const stripped = line.replace(UA_ENTRY, '');
    if (stripped.includes('appearance')) throw new Error(`${path}:${i + 1}: an appearance entry of an unknown form: ${line.trim()}`);
    // A computed row line holds only the entry, so it goes entirely.
    if (stripped.trim() !== '') out.push(stripped);
  }
  return { entries, text: out.join('\n') };
}

/**
 * UA datasets: each computed row gains exactly one appearance (auto on the control keys, none elsewhere); the control keys' declared
 * rows (both directions) and longhand lists gain auto, which their unmodelled rows held at the base; nothing else holds appearance.
 */
function stripUa(after: string, before: string, path: string): { after: string; before: string; removed: number } {
  const a = uaEntries(after, path);
  const b = uaEntries(before, path);
  const expected = (key: string): string => (CONTROL_KEYS.has(key) ? 'auto' : 'none');
  const computedRows = new Map<string, number>();
  const declared: string[] = [];
  const listed: string[] = [];
  for (const e of a.entries) {
    const at = `${path}:${e.line} ${e.section} ${e.key}`;
    if (/Computed$|^computed$/.test(e.section)) {
      if (e.value !== expected(e.key)) throw new Error(`${at}: appearance is ${JSON.stringify(e.value)}, not ${expected(e.key)}`);
      computedRows.set(`${e.section} ${e.key}`, (computedRows.get(`${e.section} ${e.key}`) ?? 0) + 1);
    } else if (/Declared$/.test(e.section)) {
      if (!CONTROL_KEYS.has(e.key) || e.value !== 'auto') throw new Error(`${at}: a declared appearance ${JSON.stringify(e.value)} on a key whose UA appearance is not auto`);
      declared.push(e.key);
    } else if (/Longhands$/.test(e.section)) {
      if (!CONTROL_KEYS.has(e.key) || e.value !== null) throw new Error(`${at}: appearance listed as a UA longhand of a key whose UA appearance is not auto`);
      listed.push(e.key);
    } else {
      throw new Error(`${at}: appearance in ${e.section}, which the migration does not touch`);
    }
  }
  for (const [row, n] of computedRows) if (n !== 1) throw new Error(`${path}: the computed row ${row} holds ${n} appearance entries`);
  // Every computed row line block gains one: count rows by their "  "key": {" openers in computed sections.
  let section = '';
  let rows = 0;
  for (const line of after.split('\n')) {
    section = SECTION.exec(line)?.[1] ?? section;
    if (/Computed$|^computed$/.test(section) && /^ {2}"[^"]+": \{$/.test(line)) rows++;
  }
  if (rows !== computedRows.size) throw new Error(`${path}: ${rows} computed rows, ${computedRows.size} with appearance`);
  // The base's unmodelled auto entries, one per key and direction, become declared entries one for one, and each key is listed once.
  const was = b.entries.filter((e) => e.section === 'userAgentUnmodelled' && e.value === 'auto').map((e) => e.key);
  if (b.entries.length !== was.length) throw new Error(`${path}: the base holds appearance outside userAgentUnmodelled's auto entries`);
  if ([...was].sort().join('|') !== [...declared].sort().join('|')) throw new Error(`${path}: the declared appearance entries [${declared.join(', ')}] are not the base's unmodelled ones [${was.join(', ')}]`);
  if ([...new Set(was)].sort().join('|') !== [...listed].sort().join('|')) throw new Error(`${path}: appearance is listed as a UA longhand of [${listed.join(', ')}], not once for each of [${[...new Set(was)].join(', ')}]`);
  return { after: a.text, before: b.text, removed: a.entries.length };
}

/** Engine inputs, line breaks and pixel manifests: no change at all. */
const unchanged = (after: string, before: string): { after: string; before: string; removed: number } => ({ after, before, removed: 0 });

const MIGRATIONS: readonly Migration[] = [
  { name: 'appearance computed values', roots: ['packages/parity/expected', 'packages/parity/expected-dpr', 'packages/parity/expected-fonts'], extension: '.json', strip: stripCapture },
  { name: 'appearance emitted declarations', roots: ['packages/parity/emitted', 'packages/parity/expected-fonts/emitted'], extension: '.css', strip: stripEmitted },
  { name: 'appearance UA values', roots: ['packages/dragon/src/ua'], extension: '.generated.ts', strip: stripUa },
  { name: 'engine inputs, unchanged', roots: ['packages/layout/vectors', 'packages/layout/break-vectors', 'packages/layout/paint-vectors'], extension: '.json', strip: unchanged },
  { name: 'Chrome line breaks, unchanged', roots: ['packages/parity/expected-breaks'], extension: '.json', strip: unchanged },
  { name: 'Chrome pixel manifests, unchanged', roots: ['packages/parity/expected-pixels'], extension: 'manifest.json', strip: unchanged },
];

/** Planted faults, each of which the check must catch: [migration index, file suffix, how the text changes]. */
const PLANTS: { readonly [name: string]: readonly [number, string, (t: string) => string] } = {
  'capture-box': [0, 'darwin-arm64/margin-collapse-body.web.json', (t) => t.replace(/"height": (\d+)/, (_m, n: string) => `"height": ${Number(n) + 1}`)],
  'capture-value': [0, 'dpr-3/margin-collapse-body.web.json', (t) => t.replace('"appearance": "none"', '"appearance": "auto"')],
  'capture-missing-key': [0, 'darwin-arm64/margin-collapse-body.web.json', (t) => t.replace(/\n *"appearance": "none",/, '')],
  'emitted-value': [1, 'emitted/margin-collapse-body.css', (t) => t.replace('  width: auto;', '  width: 10px;')],
  'emitted-appearance': [1, 'emitted/margin-collapse-body.css', (t) => t.replace(APPEARANCE, '  appearance: auto;')],
  'emitted-extra': [1, 'emitted/margin-collapse-body.css', (t) => t.replace(APPEARANCE, `${APPEARANCE}\n${APPEARANCE}`)],
  'ua-value': [2, 'chrome-145.darwin-arm64.generated.ts', (t) => t.replace('    "appearance": "none",', '    "appearance": "auto",')],
  'ua-forced': [2, 'chrome-145.darwin-arm64.generated.ts', (t) => t.replace('  "button": { ltr: { "display": "inline-block" }', '  "button": { ltr: {  }')],
  'ua-unmoved': [2, 'chrome-145.darwin-arm64.dark.generated.ts', (t) => t.replace('  "button": { ltr: { "appearance": "auto", ', '  "button": { ltr: { ')],
  'vector-output': [3, 'layout/vectors/dpr-2/margin-collapse-body.json', (t) => t.replace(/"height": (\d+)/, (_m, n: string) => `"height": ${Number(n) + 1}`)],
  'stray-file': [0, '', (t) => t],
  'pixel-manifest': [5, 'darwin-arm64/manifest.json', (t) => t.replace(/"sha256":"[0-9a-f]/, (m) => `${m.slice(0, -1)}${m.endsWith('0') ? '1' : '0'}`)],
};

const plantAt = process.argv.indexOf('--plant');
const plantName = plantAt < 0 ? null : process.argv[plantAt + 1];
if (plantName !== null && (plantName === undefined || PLANTS[plantName] === undefined)) {
  console.error(`--plant takes one of: ${Object.keys(PLANTS).join(', ')}`);
  process.exit(2);
}
const plant = plantName === null ? null : (PLANTS[plantName] as (typeof PLANTS)[string]);
let planted = false;

function git(args: readonly string[]): string {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 30 });
}

/** Every file under a root in the working tree, repository-relative. */
function filesNow(root: string, extension: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) walk(path);
      else if (name.endsWith(extension)) out.push(relative(ROOT, path));
    }
  };
  if (existsSync(join(ROOT, root))) walk(join(ROOT, root));
  return out;
}

let failures = 0;
for (const [index, m] of MIGRATIONS.entries()) {
  const atBase = git(['ls-tree', '-r', '--name-only', base, '--', ...m.roots]).split('\n').filter((f) => f.endsWith(m.extension));
  if (atBase.length === 0) {
    console.error(`${m.name}: no files under ${m.roots.join(', ')} at ${base}`);
    failures++;
    continue;
  }
  const known = new Set(atBase);
  const added = m.roots.flatMap((r) => filesNow(r, m.extension)).filter((f) => !known.has(f));
  if (plant !== null && plant[0] === index && plant[1] === '') {
    added.push(`${m.roots[0] as string}/darwin-arm64/not-a-new-fixture.web.json`);
    planted = true;
  }
  // A2 adds no fixture, so no output file may be new.
  for (const f of added) console.error(`${f}: added since ${base}; A2 adds no fixture`);
  failures += added.length;
  let changed = 0;
  let removed = 0;
  for (const f of atBase) {
    const before = git(['show', `${base}:${f}`]);
    let after: string;
    try {
      after = readFileSync(join(ROOT, f), 'utf8');
    } catch {
      console.error(`${f}: deleted since ${base}`);
      failures++;
      continue;
    }
    if (plant !== null && plant[0] === index && plant[1] !== '' && f.endsWith(plant[1]) && !planted) {
      const altered = plant[2](after);
      if (altered === after) throw new Error(`plant ${plantName as string} did not change ${f}`);
      after = altered;
      planted = true;
    }
    if (after === before) continue;
    changed++;
    try {
      const stripped = m.strip(after, before, f);
      removed += stripped.removed;
      if (stripped.after !== stripped.before) {
        console.error(`${f}: differs from ${base} beyond the ${m.name} additions`);
        failures++;
      }
    } catch (e) {
      console.error((e as Error).message);
      failures++;
    }
  }
  console.log(`${m.name}: ${atBase.length} files at ${base}, ${changed} changed, ${removed} appearance entries, every other byte identical; ${added.length} files added`);
}
if (plant !== null && !planted) throw new Error(`plant ${plantName as string} found no file to alter`);

// The UA capture's own plant: with appearance modelled, drop-unmodelled deletes button's cursor, and --check must fail naming it.
if (process.argv.includes('--ua-plant')) {
  const r = spawnSync('pnpm', ['run', 'ua:capture', '--', '--check', '--plant', 'drop-unmodelled'], { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 28 });
  const named = /FAULT light button (ltr|rtl): cursor /.test(`${r.stdout}${r.stderr}`);
  if (r.status === 0 || !named) {
    console.error(`ua:capture --check --plant drop-unmodelled: exit ${String(r.status)}, ${named ? 'names' : 'does not name'} button's cursor; it must fail naming it`);
    failures++;
  } else console.log('ua:capture --check --plant drop-unmodelled: fails naming button\'s cursor, as it must');
}
if (failures > 0) {
  console.error(`check-appearance-migration: ${failures} failures`);
  process.exit(1);
}
