// Proves the REPL-a (T051) object-fit and object-position migration of committed outputs is additive only (docs/decisions.md,
// "Adding engine fields and CSS longhands"; T051J route 2a): every file that existed at the base commit either is unchanged or
// differs only by the two new longhands, each at its initial value (fill, 50% 50%), and every file added since the base belongs
// to a fixture added since the base.
// - Chrome captures (packages/parity/expected/**, expected-dpr/**, expected-fonts/**): the computed values of every element node gain
//   "object-fit": "fill" and "object-position": "50% 50%"; with them removed the file is byte-identical to the base.
// - Emitted CSS (packages/parity/emitted/**, expected-fonts/emitted/**): every rule outside @media (which writes only differing longhands) gains "object-fit: fill;" then "object-position: 50% 50%;" after
//   padding-left; with them removed the file is byte-identical to the base, except the header's compilation digest.
// - The UA datasets (packages/dragon/src/ua/*.generated.ts): every computed row, sorted by property, gains the same two entries.
// - The engine inputs (packages/layout/vectors/**, break-vectors/**) and Chrome's line breaks (expected-breaks/**): unchanged,
//   because the replaced leaf is a new node kind.
// - The Chrome pixel manifest (expected-pixels/**/manifest.json): every base case entry unchanged; only new fixtures' cases added.
// `--plant <name>` alters one file in memory before the check, which must then fail (PLANTS below).
// Run with: node scripts/check-object-fit-migration.ts <base-commit> [--plant <name>]
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { basename, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const base = process.argv[2];
if (base === undefined || base.startsWith('--')) {
  console.error('usage: node scripts/check-object-fit-migration.ts <base-commit> [--plant <name>]');
  process.exit(2);
}

/** A migration: which committed files it covers, and how to take its additions out of one file's text. */
type Migration = {
  readonly name: string;
  readonly roots: readonly string[];
  readonly extension: string;
  /** The file text with the additions removed, formatted as the base file, and how many it removed; throws on a non-neutral addition. */
  readonly strip: (after: string, before: string, path: string) => { readonly text: string; readonly removed: number };
};

const NEUTRAL: { readonly [key: string]: string } = { 'object-fit': 'fill', 'object-position': '50% 50%' };

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

/** The indent of a JSON file written by JSON.stringify(v, null, indent), from its second line. */
function indentOf(text: string): number {
  const second = text.split('\n')[1] ?? '';
  return second.length - second.trimStart().length;
}

/** The computed values of a captured element node: every longhand, so padding-left and box-sizing among them. */
const isComputed = (v: Record<string, unknown>): boolean => typeof v['padding-left'] === 'string' && typeof v['box-sizing'] === 'string';

/** Captures: each computed object holds both keys at their initial values, right after padding-left; they are removed. */
function stripCapture(after: string, before: string, path: string): { text: string; removed: number } {
  const json = JSON.parse(after) as unknown;
  let removed = 0;
  const walk = (v: unknown, at: string): void => {
    if (Array.isArray(v)) {
      v.forEach((x, i) => walk(x, `${at}[${i}]`));
      return;
    }
    if (!isRecord(v)) return;
    if (isComputed(v)) {
      const keys = Object.keys(v);
      const i = keys.indexOf('padding-left');
      if (keys[i + 1] !== 'object-fit' || keys[i + 2] !== 'object-position') throw new Error(`${path} ${at}: object-fit and object-position do not follow padding-left`);
      for (const k of ['object-fit', 'object-position']) {
        if (v[k] !== NEUTRAL[k]) throw new Error(`${path} ${at}: ${k} is ${JSON.stringify(v[k])}, not its initial value`);
        delete v[k];
        removed++;
      }
    }
    for (const [k, x] of Object.entries(v)) walk(x, `${at}.${k}`);
  };
  walk(json, '$');
  return { text: `${JSON.stringify(json, null, indentOf(before))}\n`, removed };
}

const HEADER = /^\/\* Generated by Dragon from compilation [0-9a-f]{64}\. Do not edit\. \*\/$/;
const RULE = /^\.dg\d+ \{$/;
const FIT = '  object-fit: fill;';
const POSITION = '  object-position: 50% 50%;';

/**
 * Emitted CSS: exactly the two declarations per rule outside @media, which writes every longhand, after padding-left; a rule
 * inside @media writes only the longhands that differ (MQ-a), so it gains none. The header keeps its form with any digest.
 */
function stripEmitted(after: string, before: string, path: string): { text: string; removed: number } {
  const lines = after.split('\n');
  const was = before.split('\n');
  if (!HEADER.test(lines[0] ?? '') || !HEADER.test(was[0] ?? '')) throw new Error(`${path}: the header is not the generated-file header`);
  // Rules outside an @media block write every longhand; an @media block closes at the first "}" after its last rule.
  let rules = 0;
  let inMedia = false;
  let inRule = false;
  for (const l of lines) {
    if (l.startsWith('@media ')) inMedia = true;
    else if (RULE.test(l)) {
      inRule = true;
      if (!inMedia) rules++;
    } else if (l === '}') {
      if (inRule) inRule = false;
      else inMedia = false;
    }
  }
  const kept: string[] = [was[0] as string];
  let removed = 0;
  // Only rules outside @media gain the declarations; one inside an @media block is kept, so the base comparison then fails.
  inMedia = false;
  inRule = false;
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i] as string;
    if (line.startsWith('@media ')) inMedia = true;
    else if (RULE.test(line)) inRule = true;
    else if (line === '}') {
      if (inRule) inRule = false;
      else inMedia = false;
    }
    if (!inMedia && (line.includes('object-fit') || line.includes('object-position'))) {
      const fit = line.includes('object-fit');
      if (line !== (fit ? FIT : POSITION)) throw new Error(`${path}:${i + 1}: "${line.trim()}" is not the neutral declaration`);
      const previous = lines[i - 1] ?? '';
      if (fit ? !previous.startsWith('  padding-left: ') : previous !== FIT) throw new Error(`${path}:${i + 1}: ${fit ? 'object-fit does not follow padding-left' : 'object-position does not follow object-fit'}`);
      removed++;
      continue;
    }
    kept.push(line);
  }
  if (removed !== 2 * rules) throw new Error(`${path}: ${removed} object-fit and object-position declarations in ${rules} rules`);
  return { text: kept.join('\n'), removed };
}

const UA_FIT = '    "object-fit": "fill",';
const UA_POSITION = '    "object-position": "50% 50%",';

const UA_COMPUTED_TABLE = /^export const \w*[cC]omputed: /;
const UA_ROW = /^ {2}"[^"]+": \{$/;
const UA_ROW_END = /^ {2}\},?$/;

/**
 * UA datasets: every row of every computed table (sorted by property) gains exactly the two entries, object-position right after
 * object-fit, and nothing else changes; a row missing them, or holding them twice, fails.
 */
function stripUa(after: string, _before: string, path: string): { text: string; removed: number } {
  const lines = after.split('\n');
  const kept: string[] = [];
  let removed = 0;
  let inTable = false;
  let row: { readonly line: number; pairs: number } | null = null;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] as string;
    if (UA_COMPUTED_TABLE.test(line)) inTable = true;
    else if (line === '};') inTable = false;
    else if (inTable && UA_ROW.test(line)) row = { line: i + 1, pairs: 0 };
    else if (row !== null && UA_ROW_END.test(line)) {
      if (row.pairs !== 1) throw new Error(`${path}:${row.line}: a computed row holds ${row.pairs} object-fit and object-position pairs, not 1`);
      row = null;
    }
    if (line.includes('"object-fit"') || line.includes('"object-position"')) {
      if (row === null) throw new Error(`${path}:${i + 1}: an object-fit or object-position entry outside a computed row`);
      if (line.includes('"object-fit"')) row.pairs++;
      const fit = line.includes('"object-fit"');
      if (line !== (fit ? UA_FIT : UA_POSITION)) throw new Error(`${path}:${i + 1}: "${line.trim()}" is not the neutral entry`);
      if (fit ? lines[i + 1] !== UA_POSITION : lines[i - 1] !== UA_FIT) throw new Error(`${path}:${i + 1}: object-fit and object-position are not adjacent`);
      removed++;
      continue;
    }
    kept.push(line);
  }
  return { text: kept.join('\n'), removed };
}

/** Engine inputs and break captures: no addition at all. */
const unchanged = (after: string): { text: string; removed: number } => ({ text: after, removed: 0 });

/** The pixel manifest: each set keeps every base case entry as it was and only gains the new fixtures' cases. */
function stripPixelManifest(after: string, before: string, path: string): { text: string; removed: number } {
  type Manifest = { sets: { dpr: number; cases: { case: string }[] }[] };
  const a = JSON.parse(after) as Manifest;
  const b = JSON.parse(before) as Manifest;
  let removed = 0;
  for (const set of a.sets) {
    const kept = set.cases.filter((c) => !ofNewFixture(`${c.case}.png`));
    removed += set.cases.length - kept.length;
    set.cases = kept;
  }
  if (JSON.stringify(a) !== JSON.stringify(b)) throw new Error(`${path}: differs from the base beyond the new fixtures' cases`);
  return { text: before, removed };
}

const MIGRATIONS: readonly Migration[] = [
  { name: 'object-fit and object-position computed values (T051)', roots: ['packages/parity/expected', 'packages/parity/expected-dpr', 'packages/parity/expected-fonts'], extension: '.json', strip: stripCapture },
  { name: 'object-fit and object-position emitted declarations (T051)', roots: ['packages/parity/emitted', 'packages/parity/expected-fonts/emitted'], extension: '.css', strip: stripEmitted },
  { name: 'object-fit and object-position UA computed values (T051)', roots: ['packages/dragon/src/ua'], extension: '.generated.ts', strip: stripUa },
  { name: 'engine inputs, unchanged (T051 replaced leaf kind)', roots: ['packages/layout/vectors', 'packages/layout/break-vectors'], extension: '.json', strip: unchanged },
  { name: 'Chrome line breaks, unchanged', roots: ['packages/parity/expected-breaks'], extension: '.json', strip: unchanged },
  { name: 'Chrome pixel manifest, base cases unchanged', roots: ['packages/parity/expected-pixels'], extension: 'manifest.json', strip: stripPixelManifest },
];

/** Planted faults, each of which the check must catch: [migration index, file suffix, how the text changes]. */
const PLANTS: { readonly [name: string]: readonly [number, string, (t: string) => string] } = {
  'capture-box': [0, 'darwin-arm64/margin-collapse-body.web.json', (t) => t.replace(/"height": (\d+)/, (_m, n: string) => `"height": ${Number(n) + 1}`)],
  'capture-fit': [0, 'dpr-3/margin-collapse-body.web.json', (t) => t.replace('"object-fit": "fill"', '"object-fit": "cover"')],
  'capture-missing-key': [0, 'darwin-arm64/margin-collapse-body.web.json', (t) => t.replace('        "object-position": "50% 50%",\n', '')],
  'emitted-value': [1, 'emitted/margin-collapse-body.css', (t) => t.replace('  width: auto;', '  width: 10px;')],
  'emitted-position': [1, 'emitted/margin-collapse-body.css', (t) => t.replace(POSITION, '  object-position: 0% 0%;')],
  'emitted-extra': [1, 'emitted/margin-collapse-body.css', (t) => t.replace(FIT, `${FIT}\n${FIT}`)],
  'emitted-media': [1, 'emitted/media-max-width.css', (t) => t.replace(/(@media [^\n]*\n\.dg\d+ \{\n)/, `$1${FIT}\n${POSITION}\n`)],
  'ua-value': [2, 'chrome-145.darwin-arm64.generated.ts', (t) => t.replace(UA_POSITION, '    "object-position": "0% 0%",')],
  'ua-row-missing': [2, 'chrome-145.darwin-arm64.generated.ts', (t) => t.replace(`${UA_FIT}\n${UA_POSITION}\n`, '')],
  'emitted-moved-to-media': [1, 'emitted/media-max-width.css', (t) => t.replace(`${FIT}\n${POSITION}\n`, '').replace(/(@media [^\n]*\n\.dg\d+ \{\n)/, `$1${FIT}\n${POSITION}\n`)],
  'vector-output': [3, 'layout/vectors/dpr-2/margin-collapse-body.json', (t) => t.replace(/"height": (\d+)/, (_m, n: string) => `"height": ${Number(n) + 1}`)],
  'stray-file': [0, '', (t) => t],
  'pixel-manifest': [5, 'darwin-arm64/manifest.json', (t) => t.replace(/"sha256":"[0-9a-f]/, (m) => `${m.slice(0, -1)}${m.endsWith('0') ? '1' : '0'}`)],
};

const plantAt = process.argv.indexOf('--plant');
const plantName = plantAt < 0 ? null : process.argv[plantAt + 1];
if (plantName !== null && (plantName === undefined || PLANTS[plantName] === undefined)) {
  console.error(`--plant takes one of: ${Object.keys(PLANTS).join(', ')}`);
  process.exit(2);
}
const plant = plantName === null ? null : (PLANTS[plantName] as (typeof PLANTS)[string]);
let planted = false;

function git(args: readonly string[]): string {
  return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 30 });
}

/** Every file under a root in the working tree, repository-relative. */
function filesNow(root: string, extension: string): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) walk(path);
      else if (name.endsWith(extension)) out.push(relative(ROOT, path));
    }
  };
  if (existsSync(join(ROOT, root))) walk(join(ROOT, root));
  return out;
}

// Fixtures added since the base: only their outputs may be new files.
const fixtureIds = (names: readonly string[]): Set<string> => new Set(names.filter((n) => n.endsWith('.html')).map((n) => basename(n, '.html')));
const fixturesAtBase = fixtureIds(git(['ls-tree', '--name-only', `${base}:packages/parity/fixtures`]).split('\n'));
const newFixtures = [...fixtureIds(readdirSync(join(ROOT, 'packages/parity/fixtures')))].filter((id) => !fixturesAtBase.has(id));
const ofNewFixture = (path: string): boolean => {
  const name = basename(path);
  return newFixtures.some((id) => name.startsWith(`${id}.`) || name.startsWith(`${id}-rtl.`));
};

let failures = 0;
for (const [index, m] of MIGRATIONS.entries()) {
  const atBase = git(['ls-tree', '-r', '--name-only', base, '--', ...m.roots]).split('\n').filter((f) => f.endsWith(m.extension));
  const known = new Set(atBase);
  const added = m.roots.flatMap((r) => filesNow(r, m.extension)).filter((f) => !known.has(f));
  if (plant !== null && plant[0] === index && plant[1] === '') {
    added.push(`${m.roots[0] as string}/darwin-arm64/not-a-new-fixture.web.json`);
    planted = true;
  }
  const stray = added.filter((f) => !ofNewFixture(f));
  for (const f of stray) console.error(`${f}: added since ${base}, but no fixture added since then owns it`);
  failures += stray.length;
  let changed = 0;
  let removed = 0;
  for (const f of atBase) {
    const before = git(['show', `${base}:${f}`]);
    let after: string;
    try {
      after = readFileSync(join(ROOT, f), 'utf8');
    } catch {
      console.error(`${f}: deleted since ${base}`);
      failures++;
      continue;
    }
    if (plant !== null && plant[0] === index && plant[1] !== '' && f.endsWith(plant[1]) && !planted) {
      const altered = plant[2](after);
      if (altered === after) throw new Error(`plant ${plantName as string} did not change ${f}`);
      after = altered;
      planted = true;
    }
    if (after === before) continue;
    changed++;
    try {
      const stripped = m.strip(after, before, f);
      removed += stripped.removed;
      if (stripped.text !== before) {
        console.error(`${f}: differs from ${base} beyond the ${m.name} additions`);
        failures++;
      }
    } catch (e) {
      console.error((e as Error).message);
      failures++;
    }
  }
  console.log(`${m.name}: ${atBase.length} files at ${base}, ${changed} changed, ${removed} neutral additions, every other byte identical; ${added.length} files added, all from the ${newFixtures.length} new fixtures`);
}
if (plant !== null && !planted) throw new Error(`plant ${plantName as string} found no file to alter`);
if (failures > 0) {
  console.error(`check-object-fit-migration: ${failures} failures`);
  process.exit(1);
}
