// Writes THIRD_PARTY_NOTICES.md from docs/ports.json (the copyright lines and licence texts of the Chrome files Dragon cites) and
// vendor/harfbuzz/COPYING. packages/parity/test/chrome-ports.test.ts fails when the file differs from what this writes.
// Run with: node scripts/gen-third-party-notices.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const NOTICES_PATH = 'THIRD_PARTY_NOTICES.md';

export interface NoticeEntry { upstream: string; licence: string; noticeText?: string; copyright: string }
export interface NoticeRegistry { tag: string; skiaRevision: string; entries: readonly NoticeEntry[]; licenceTexts: Readonly<Record<string, string>> }

const TITLES: [RegExp, string][] = [
  [/^chromium-bsd$/, 'Chromium: BSD 3-Clause (the Chromium LICENSE file)'],
  [/^skia-bsd$/, 'Skia: BSD 3-Clause (the Skia LICENSE file)'],
  [/^header-bsd-\d+$/, 'Chromium files with a BSD licence in their own header'],
  [/^rapidhash-bsd-2$/, 'rapidhash: BSD 2-Clause'],
];

/** The id of the licence text that covers an entry, or null for an LGPL entry (no Dragon code comes from those). */
export function noticeTextOf(e: NoticeEntry): string | null {
  if (e.licence === 'lgpl') return null;
  if (e.noticeText === undefined) throw new Error(`${e.upstream}: no noticeText for licence ${e.licence}`);
  return e.noticeText;
}

function titleOf(id: string): string {
  const t = TITLES.find(([re]) => re.test(id));
  if (!t) throw new Error(`licence text ${id} has no title`);
  return t[1];
}

/** THIRD_PARTY_NOTICES.md for a registry and HarfBuzz's COPYING. */
export function thirdPartyNotices(registry: NoticeRegistry, harfbuzzCopying: string): string {
  if (typeof registry.licenceTexts !== 'object' || registry.licenceTexts === null) throw new Error('docs/ports.json: no licenceTexts');
  if (!Array.isArray(registry.entries)) throw new Error('docs/ports.json: no entries');
  for (const e of registry.entries) {
    if (typeof e.copyright !== 'string' || !e.copyright.startsWith('Copyright')) throw new Error(`${e.upstream}: no copyright line`);
  }
  for (const [id, text] of Object.entries(registry.licenceTexts)) if (typeof text !== 'string' || text.trim() === '') throw new Error(`licence text ${id} is empty`);
  if (!harfbuzzCopying.includes('Permission is hereby granted')) throw new Error('vendor/harfbuzz/COPYING is not the HarfBuzz MIT licence');
  const groups = new Map<string, NoticeEntry[]>();
  for (const id of Object.keys(registry.licenceTexts)) groups.set(id, []);
  for (const e of registry.entries) {
    const id = noticeTextOf(e);
    if (id === null) continue;
    const g = groups.get(id);
    if (!g) throw new Error(`${e.upstream}: noticeText ${id} is not in licenceTexts`);
    g.push(e);
  }
  const out: string[] = [
    '# Third-party notices',
    '',
    '<!-- Generated by scripts/gen-third-party-notices.ts from docs/ports.json and vendor/harfbuzz/COPYING; do not edit. -->',
    '',
    "Dragon is under the MIT licence (LICENSE). Parts of Dragon's TypeScript are ported from, or follow, source files of Chromium",
    `${registry.tag} (Skia at revision ${registry.skiaRevision}). docs/ports.json lists each file and the Dragon code that cites it.`,
    'Those files are under the licences below, with the copyright lines from their headers. The text shaper builds HarfBuzz',
    '(vendor/harfbuzz), which is under the licence at the end.',
  ];
  for (const [id, entries] of groups) {
    if (entries.length === 0) continue;
    out.push('', `## ${titleOf(id)} (${id})`, '');
    for (const e of [...entries].sort((a, b) => a.upstream.localeCompare(b.upstream))) out.push(`- \`${e.upstream}\`: ${e.copyright}`);
    out.push('', '```', registry.licenceTexts[id]!.replace(/\n$/, ''), '```');
  }
  out.push('', '## HarfBuzz: "Old MIT" (vendor/harfbuzz/COPYING)', '', '```', harfbuzzCopying.replace(/\n$/, ''), '```', '');
  return out.join('\n');
}

export function currentNotices(root: string = ROOT): string {
  const registry = JSON.parse(readFileSync(join(root, 'docs', 'ports.json'), 'utf8')) as NoticeRegistry;
  return thirdPartyNotices(registry, readFileSync(join(root, 'vendor', 'harfbuzz', 'COPYING'), 'utf8'));
}

if (import.meta.main) {
  writeFileSync(join(ROOT, NOTICES_PATH), currentNotices());
  console.log(`wrote ${NOTICES_PATH}`);
}
