// Generates packages/layout/src/script-data.ts, the pinned Unicode Script property (UAX #24) behind the engine's Latin text scope
// (docs/goals/milestone-2-proof/notes/T056-txt1a-spec.md §2 R4): text is in scope when every code point is Latin, Common or
// Inherited. Unicode 16.0.0 is the version of ICU 77, the ICU in Chrome 145 (scripts/gen-linebreak-data.ts has the evidence).
//
// Run with: node scripts/gen-script-data.ts [--check]
//   Reads vendor/unicode/16.0.0/Scripts.txt, which must match its pinned SHA-256. --check requires the committed file to be
//   byte-identical to a fresh generation.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'packages/layout/src/script-data.ts');
const UNICODE_VERSION = '16.0.0';
const SOURCE = { path: `vendor/unicode/${UNICODE_VERSION}/Scripts.txt`, url: `https://www.unicode.org/Public/${UNICODE_VERSION}/ucd/Scripts.txt`, sha256: '9e88f0a677df47311106340be8ede2ecdacd9c1c931831218d2be6d5508e0039' };
const MAX_CP = 0x10ffff;
/** Code points Scripts.txt does not list have the value Unknown (UAX #24 §2). */
const UNKNOWN = 'Unknown';

function load(): string {
  const bytes = readFileSync(join(ROOT, SOURCE.path));
  const sha = createHash('sha256').update(bytes).digest('hex');
  if (sha !== SOURCE.sha256) throw new Error(`${SOURCE.path}: sha256 ${sha}, pinned ${SOURCE.sha256}`);
  return bytes.toString('utf8');
}

/** One script name per code point, from the file's ranges. */
function parse(text: string): string[] {
  const values = new Array<string>(MAX_CP + 1).fill(UNKNOWN);
  for (const raw of text.split('\n')) {
    const line = raw.replace(/#.*/, '').trim();
    if (line === '') continue;
    const [range, name] = line.split(';').map((s) => s.trim()) as [string, string];
    const [a, b] = range.split('..').map((h) => parseInt(h, 16)) as [number, number | undefined];
    for (let cp = a; cp <= (b ?? a); cp++) {
      if (values[cp] !== UNKNOWN) throw new Error(`U+${cp.toString(16)} is listed twice`);
      values[cp] = name;
    }
  }
  return values;
}

function generate(): string {
  const values = parse(load());
  // Code order: Unknown, Common, Inherited, Latin, then every other script in the order it first appears.
  const names = [UNKNOWN, 'Common', 'Inherited', 'Latin'];
  for (const v of values) if (!names.includes(v)) names.push(v);
  const code = new Map(names.map((n, i) => [n, i]));
  const starts: number[] = [];
  const runValues: number[] = [];
  for (let cp = 0; cp <= MAX_CP; cp++) {
    const c = code.get(values[cp] as string) as number;
    if (runValues.length === 0 || runValues[runValues.length - 1] !== c) {
      starts.push(cp);
      runValues.push(c);
    }
  }
  const list = (xs: readonly number[]): string => {
    const lines: string[] = [];
    for (let i = 0; i < xs.length; i += 16) lines.push(`  ${xs.slice(i, i + 16).join(', ')},`);
    return lines.join('\n');
  };
  return [
    `// GENERATED by scripts/gen-script-data.ts from the Unicode ${UNICODE_VERSION} UCD. Do not edit; run node scripts/gen-script-data.ts.`,
    '// Unicode 16.0.0 is the version of ICU 77, the ICU in Chrome 145 (scripts/gen-linebreak-data.ts has the evidence).',
    `// ${SOURCE.url} sha256 ${SOURCE.sha256} (vendored at ${SOURCE.path})`,
    '// The Script property (UAX #24) as sorted runs; Script_Extensions is not included.',
    '',
    `export const SCRIPT_UNICODE_VERSION = '${UNICODE_VERSION}';`,
    '',
    '/** Script names as Scripts.txt writes them, indexed by script code. Code 0 is Unknown, for code points the file does not list. */',
    `export const SCRIPT_NAMES: readonly string[] = [${names.map((n) => `'${n}'`).join(', ')}];`,
    'export const SCRIPT_UNKNOWN = 0;',
    'export const SCRIPT_COMMON = 1;',
    'export const SCRIPT_INHERITED = 2;',
    'export const SCRIPT_LATIN = 3;',
    '',
    '/** The first code point of each run of one script. */',
    'export const SCRIPT_STARTS: readonly number[] = [',
    list(starts),
    '];',
    '',
    '/** The script code of each run in SCRIPT_STARTS. */',
    'export const SCRIPT_VALUES: readonly number[] = [',
    list(runValues),
    '];',
    '',
    '/** The index of the last start at or before cp (SCRIPT_STARTS[0] is 0), by a power-of-two search, which needs no rounding. */',
    'function scriptRunIndex(cp: number): number {',
    '  let step = 1;',
    '  while (step * 2 <= SCRIPT_STARTS.length) step = step * 2;',
    '  let pos = 0;',
    '  while (step >= 1) {',
    '    if (pos + step < SCRIPT_STARTS.length && (SCRIPT_STARTS[pos + step] as number) <= cp) pos = pos + step;',
    '    step = step / 2;',
    '  }',
    '  return pos;',
    '}',
    '',
    '/** The Script property code of a code point (an index into SCRIPT_NAMES). */',
    'export function scriptCode(cp: number): number {',
    '  return SCRIPT_VALUES[scriptRunIndex(cp)] as number;',
    '}',
    '',
    '/** R4 Latin scope: every code point of the text has Script Latin, Common or Inherited. */',
    'export function isLatinText(text: string): boolean {',
    '  for (const ch of text) {',
    '    const s = scriptCode(ch.codePointAt(0) as number);',
    '    if (s !== SCRIPT_LATIN && s !== SCRIPT_COMMON && s !== SCRIPT_INHERITED) return false;',
    '  }',
    '  return true;',
    '}',
    '',
  ].join('\n');
}

const fresh = generate();
if (process.argv.includes('--check')) {
  const committed = readFileSync(OUT, 'utf8');
  if (committed !== fresh) {
    console.error('packages/layout/src/script-data.ts differs from a fresh generation; run node scripts/gen-script-data.ts');
    process.exit(1);
  }
  console.log('script-data.ts is byte-identical to a fresh generation');
} else {
  writeFileSync(OUT, fresh);
  console.log(`wrote ${OUT}`);
}
