import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext();
const page = await ctx.newPage();
const cdp = await ctx.newCDPSession(page);
await cdp.send('Animation.enable');
await cdp.send('Animation.setPlaybackRate', { playbackRate: 0 });
await page.setContent('<div>x</div>');
console.log('after setContent', await page.evaluate(() => document.timeline.currentTime));
await page.evaluate(async () => { await document.fonts.ready; await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r))); });
console.log('after raf', await page.evaluate(() => document.timeline.currentTime));
await b.close();
