// Writes docs/research/text-spike/gate-report.md: the gate result, the planted-fault controls and the
// stripped binary size per ABI. Needs `zig build` output in packages/text-shaper/zig-out and, for the
// iOS dylib sizes, Xcode's clang and strip.
// Usage: node packages/text-shaper/scripts/report.ts
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SPIKE_DIR, loadReference, runGate } from '../src/gate.ts';
import type { CaseResult, GateOptions } from '../src/gate.ts';
import { DEFAULT_WASM_PATH, DragonHB } from '../src/wasm.ts';

const pkg = fileURLToPath(new URL('..', import.meta.url));
const out = join(pkg, 'zig-out');
const ref = loadReference();
const hb = DragonHB.load();

const results = runGate(ref, hb);
const exact = (rs: readonly CaseResult[]): number => rs.filter((r) => r.exact).length;
const lines = results.reduce((n, r) => n + r.lines, 0);
const groups = new Map<string, [number, number, number]>();
for (const r of results) {
  const [font, para] = r.id.split('/') as [string, string];
  const g = font === 'NotoSansJP' ? (para === 'prose' ? 'Noto Sans JP, Latin prose' : 'Noto Sans JP, Japanese') : font === 'InterVF' ? 'Inter variable (opsz auto)' : `${font}`;
  const v = groups.get(g) ?? [0, 0, 0];
  v[1]++;
  v[2] += r.lines;
  if (r.exact) v[0]++;
  groups.set(g, v);
}

const faults: ReadonlyArray<readonly [string, GateOptions]> = [
  ['Glyph advances summed in float, not InlineLayoutUnit (16.16 integer)', { faults: { floatAccumulation: true } }],
  ['Positions rounded to whole pixels (Blink without subpixel positioning)', { faults: { wholePixelPositions: true } }],
  ['`kern` off', { faults: { noKerning: true } }],
  ['No reshaping at the start of wrapped lines', { faults: { noReshapeAtLineStart: true } }],
  ['No HanKerning (`halt` for text-spacing-trim)', { noHanKerning: true }],
];
const faultRows = faults.map(([name, o]) => {
  const r = runGate(ref, hb, o);
  return `| ${name} | ${exact(r)}/${r.length} | ${r.reduce((n, x) => n + x.lineDiffs.length, 0)} |`;
});

const size = (p: string): number => statSync(p).size;
const kb = (n: number): string => `${(n / 1024).toFixed(0)} KiB`;
const sha = (p: string): string => createHash('sha256').update(readFileSync(p)).digest('hex');

const wasm = join(out, 'wasm', 'dragon_hb.wasm');
if (sha(wasm) !== sha(DEFAULT_WASM_PATH)) throw new Error('wasm/dragon_hb.wasm is not the zig-out build; run `pnpm --filter @dragon/text-shaper build:wasm`');

// iOS ships static libraries; the per-ABI cost is what they add to a linked, stripped image.
const tmp = mkdtempSync(join(tmpdir(), 'dragon-hb-size-'));
const iosDylib = (slice: string, sdk: string, target: string): number => {
  const dylib = join(tmp, `${slice}.dylib`);
  execFileSync('xcrun', ['-sdk', sdk, 'clang', '-target', target, '-dynamiclib', '-Wl,-dead_strip', '-Wl,-all_load', join(out, 'ios', slice, 'libdragon_hb.a'), '-o', dylib]);
  execFileSync('xcrun', ['strip', '-x', dylib]);
  return size(dylib);
};

const sizes = (() => {
  try {
    return [
      ['WASM (wasm32-wasi reactor)', 'wasm/dragon_hb.wasm', size(wasm), '-'],
      ['iOS device arm64', 'DragonHB.xcframework/ios-arm64', size(join(out, 'ios', 'ios-arm64', 'libdragon_hb.a')), kb(iosDylib('ios-arm64', 'iphoneos', 'arm64-apple-ios15.0'))],
      ['iOS simulator arm64', 'DragonHB.xcframework/ios-arm64-simulator', size(join(out, 'ios', 'ios-arm64-simulator', 'libdragon_hb.a')), kb(iosDylib('ios-arm64-simulator', 'iphonesimulator', 'arm64-apple-ios15.0-simulator'))],
      ['Android arm64-v8a', 'android/arm64-v8a/libdragon_hb.so', size(join(out, 'android', 'arm64-v8a', 'libdragon_hb.so')), '-'],
      ['Android x86_64', 'android/x86_64/libdragon_hb.so', size(join(out, 'android', 'x86_64', 'libdragon_hb.so')), '-'],
    ] as const;
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
})();

const md = `# TXT1-0 gate report: HarfBuzz in WASM against Chrome 145

Generated by \`node packages/text-shaper/scripts/report.ts\`. The gate itself runs in \`pnpm test\`
(packages/text-shaper/test/gate.test.ts).

## Result

**${exact(results)}/${results.length} cases exact**: every one of the ${lines} line widths and all ${results.length} nowrap widths are equal to
Chrome's, in LayoutUnits (1/64 px). No tolerance is applied.

| Group | Cases exact | Lines |
|---|---|---|
${[...groups].map(([g, [ok, n, l]]) => `| ${g} | ${ok}/${n} | ${l} |`).join('\n')}

## What is compared

The reference is the text spike's Chrome 145.0.7632.6 run (macOS, DPR 1), imported into
\`gate/chrome-145.json\` by \`packages/text-shaper/scripts/import-spike.ts docs/research/text-spike/out\`. The capture scripts are in \`chrome/\`
(\`measure.mjs\`, \`opps.mjs\`, \`page.html\`), their raw output in \`out/\`, and the SHA-256 of the fonts Chrome loaded in
\`chrome/loaded-fonts.sha256\`:

- **Per line:** the width of the Range client rect over [line start, line end without trailing spaces), in the
  paragraph at \`white-space: normal\`, \`text-align: start\`. Line breaks are taken from Chrome: the gate tests
  shaping and advance arithmetic, not line breaking. At a soft hyphen break the rect also covers the generated
  hyphen, so the gate adds the hyphen's own width.
- **Per font, paragraph and size:** the width of a \`white-space: nowrap\` span.
- **Break opportunities** (a \`width: 0\` layout) are used only to decide whether Blink's line-end
  text-spacing-trim extension was possible (\`LazyLineBreakIterator::IsBreakable\`).

## The pipeline, as Blink runs it

1. **Shim (\`dragon_hb.zig\`) over unmodified HarfBuzz** at \`fa2908bf16d2ccd6623f4d575455fea72a1a722b\`, compiled with
   Chromium's HarfBuzz defines and \`-ffp-contract=off\`. Faces and fonts are set up as \`harfbuzz_face.cc\` does: an
   \`hb_ot\` font with the variation coordinates, a sub-font with the scale \`SkiaScalarToHarfBuzzPosition(size)\` and ptem,
   and an advance callback.
2. **Advance:** \`trunc(float(units * size / upem) * 65536)\`: Core Text's CGFloat advance, stored by Skia as a
   float, kept unrounded (subpixel on macOS), converted by \`SkiaScalarToHarfBuzzPosition\` (\`ClampTo<int>(v * 65536)\`).
   For a variable instance, \`units\` is the hmtx advance plus the **unrounded** HVAR delta at Core Text's
   normalized coordinates (see below). Fonts with \`trak\` and no \`sbix\` keep HarfBuzz's advances, as on macOS.
3. **Variations:** Blink's \`FontCustomPlatformData\` rules: \`wght\`, \`wdth\` and \`slnt\` from the request, clamped to
   the axis; \`opsz\` = the specified size when \`font-optical-sizing: auto\`.
4. **Shaping:** per RunSegmenter range (script runs by Blink's \`ScriptRunIterator\`; 8-bit text is one Latin run), the
   whole paragraph as context, the style's features (\`chws\` for \`text-spacing-trim: normal\`) plus HanKerning's
   \`halt\` ranges.
5. **Blink arithmetic (TypeScript, \`src/blink.ts\`):** a run's width is the InlineLayoutUnit (int64 16.16) sum of its
   advances, a negative sum clamped to zero, converted to float; a line is a ShapeResultView of the paragraph with the start of a wrapped line
   reshaped when it is not safe to break, and the end reshaped only when the break is not at a space
   (\`text-align: start\` sets DontReshapeEndIfAtSpace); a part's width is the unclamped InlineLayoutUnit sum of its
   advances; part widths are summed in float; the line width is
   \`LayoutUnit::FromFloatCeil\`.

Only integers cross the shim boundary: glyph id, cluster, x/y advance, x/y offset and the glyph flags.

## The gate can fail

Each planted fault is a deliberate departure from Blink; the gate must catch all of them (also asserted in
\`gate.test.ts\`).

| Planted fault | Cases exact | Lines off |
|---|---|---|
${faultRows.join('\n')}

Two advance-function mistakes found while building the shim, both fixed in \`dragon_hb.zig\`, failed the gate
on Inter variable only (the Latin static fonts were already 480/480):

- HarfBuzz's own variable advances round the HVAR delta to a whole font unit: 15/60 Inter variable cases exact.
- Unrounded deltas at HarfBuzz's normalized coordinates (1821 for \`opsz\` 16, rounded through 16.16) instead of Core
  Text's (1820, \`round(normalized * 16384)\`): 45/60. HarfBuzz keeps its own coordinates for GPOS deltas, as in
  Chrome, where HarfBuzz receives the design coordinates from Core Text's typeface.

## Binary size per ABI (stripped)

| Target | Artifact | Size | Linked into a stripped dylib |
|---|---|---|---|
${sizes.map(([t, a, s, d]) => `| ${t} | ${a} | ${kb(s)} (${s} bytes) | ${d} |`).join('\n')}

The iOS xcframework holds static libraries (no libc++ dependency); the last column is what one adds to a linked,
stripped image. The Android libraries depend only on libc and libm (API 31) and use 16 KB segment alignment.
\`wasm/dragon_hb.wasm\` is committed (SHA-256 \`${sha(DEFAULT_WASM_PATH)}\`); \`zig build wasm\` reproduces it
byte for byte.

## Limits of this gate

- **Fonts:** HarfBuzz's glyph extents stand in for Skia's Core Text path bounds. In shaping, Blink uses those bounds only for
  fallback mark positioning and for HanKerning's punctuation classes, which the gate exercises (Noto Sans JP).
- **Unicode data:** HarfBuzz's built-in UCD instead of Chrome's ICU; script runs use V8's ICU.
- **Not covered:** font fallback (the gate refuses text a font cannot render), emoji, combining marks, vertical
  text, RTL, letter/word spacing, justification, \`text-align\` other than start, variable fonts without HVAR,
  and Core Text's synthesized U+2010/U+2011 glyphs.
- **Android .so builds need an NDK** (\`-Dandroid-ndk=<path>\` or \`ANDROID_NDK_HOME\`); the sizes above used NDK r27c
  (27.2.12479018).

Fonts: \`fonts/README.md\`. Chrome sources read: \`harfbuzz_face.cc\`, \`skia_text_metrics.cc\`,
\`font_custom_platform_data.cc\`, \`web_font_typeface_factory.cc\`, \`harfbuzz_shaper.cc\`, \`shape_result.cc\`,
\`shape_result_view.cc\`, \`shaping_line_breaker.cc\`, \`line_breaker.cc\`, \`fragment_item.cc\`, \`layout_text.cc\`,
\`script_run_iterator.cc\`, \`han_kerning.cc\`, \`font_features.cc\` and \`layout_unit.h\` at tag 145.0.7632.6.
`;

writeFileSync(join(SPIKE_DIR, 'gate-report.md'), md);
console.log(`wrote ${join(SPIKE_DIR, 'gate-report.md')}: ${exact(results)}/${results.length}`);
