// The committed snapshot (snapshot/tailwind-<version>.json, generated by pnpm run tw:sweep) and its summary. One utility per line,
// so a regenerated snapshot diffs by utility. Per target an outcome is "supported", ["refused", code, group, at, fix index] (with a
// sixth element "chrome-parses" when Dragon calls the CSS invalid but Chrome keeps it), ["invalid", why] or ["mismatch", problems];
// "=web" and "=ios" repeat an earlier target's outcome. Fix messages are listed once, in "fixes".
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { CATEGORIES } from './categories.ts';
import type { Category } from './categories.ts';
import type { Target } from './dragon.ts';
import { TARGETS } from './dragon.ts';
import type { Outcome, UtilityRecord } from './sweep.ts';
import { TAILWIND_VERSION } from './tailwind.ts';

export const SNAPSHOT_SCHEMA = 'dragon/tailwind-sweep@1';
export const SNAPSHOT_DIR = join(import.meta.dirname, '..', 'snapshot');
export const SNAPSHOT_PATH = join(SNAPSHOT_DIR, `tailwind-${TAILWIND_VERSION}.json`);
export const SUMMARY_PATH = join(SNAPSHOT_DIR, 'summary.md');

type Encoded = string | readonly (string | number | readonly string[])[];
type Line = { readonly u: string; readonly r: string; readonly c: Category; readonly with?: readonly string[]; readonly web: Encoded; readonly ios: Encoded; readonly android: Encoded; readonly published: readonly string[] | { readonly [T in Target]: readonly string[] } };

const same = (a: unknown, b: unknown): boolean => JSON.stringify(a) === JSON.stringify(b);

export function serialize(records: readonly UtilityRecord[], meta: { readonly chrome: string }): string {
  const fixes: string[] = [];
  const fixIndex = new Map<string, number>();
  const encode = (o: Outcome): Encoded => {
    switch (o.status) {
      case 'supported':
        return 'supported';
      case 'refused': {
        let i = fixIndex.get(o.fix);
        if (i === undefined) {
          i = fixes.length;
          fixes.push(o.fix);
          fixIndex.set(o.fix, i);
        }
        return o.chromeParses === true ? ['refused', o.code, o.group, o.at, i, 'chrome-parses'] : ['refused', o.code, o.group, o.at, i];
      }
      case 'invalid':
        return ['invalid', o.why];
      case 'mismatch':
        return ['mismatch', o.problems];
    }
  };
  const lines = records.map((r) => {
    const web = encode(r.outcomes.web);
    const ios = same(r.outcomes.ios, r.outcomes.web) ? '=web' : encode(r.outcomes.ios);
    const android = same(r.outcomes.android, r.outcomes.web) ? '=web' : same(r.outcomes.android, r.outcomes.ios) ? '=ios' : encode(r.outcomes.android);
    const published = TARGETS.every((t) => same(r.published[t], r.published.web)) ? r.published.web : r.published;
    const line: Line = { u: r.utility, r: r.root, c: r.category, ...(r.with === null ? {} : { with: r.with }), web, ios, android, published };
    return JSON.stringify(line);
  });
  const head = { schema: SNAPSHOT_SCHEMA, tailwind: TAILWIND_VERSION, chrome: meta.chrome, utilities: records.length };
  return `{\n"meta": ${JSON.stringify(head)},\n"fixes": ${JSON.stringify(fixes)},\n"utilities": [\n${lines.join(',\n')}\n]\n}\n`;
}

export function deserialize(text: string): { meta: { schema: string; tailwind: string; chrome: string; utilities: number }; records: UtilityRecord[] } {
  const raw = JSON.parse(text) as { meta: { schema: string; tailwind: string; chrome: string; utilities: number }; fixes: string[]; utilities: Line[] };
  if (raw.meta.schema !== SNAPSHOT_SCHEMA) throw new Error(`snapshot schema ${raw.meta.schema}, expected ${SNAPSHOT_SCHEMA}`);
  const decode = (e: Encoded, prior: Partial<Record<Target, Outcome>>): Outcome => {
    if (e === 'supported') return { status: 'supported' };
    if (e === '=web' || e === '=ios') {
      const o = prior[e.slice(1) as Target];
      if (o === undefined) throw new Error(`${e} before that target`);
      return o;
    }
    if (typeof e === 'string') throw new Error(`unknown outcome ${e}`);
    const [kind, a, b, c, d, f] = e;
    if (kind === 'refused') {
      const fix = raw.fixes[d as number];
      if (fix === undefined) throw new Error(`fix index ${String(d)} out of range`);
      const base = { status: 'refused', code: a as string, group: b as string, at: c as string, fix } as const;
      return f === 'chrome-parses' ? { ...base, chromeParses: true } : base;
    }
    if (kind === 'invalid') return { status: 'invalid', why: a as string };
    if (kind === 'mismatch') return { status: 'mismatch', problems: a as string[] };
    throw new Error(`unknown outcome ${String(kind)}`);
  };
  const records = raw.utilities.map((l): UtilityRecord => {
    const prior: Partial<Record<Target, Outcome>> = {};
    for (const t of TARGETS) prior[t] = decode(l[t], prior);
    const published = Array.isArray(l.published) ? { web: l.published, ios: l.published, android: l.published } : (l.published as { [T in Target]: readonly string[] });
    return { utility: l.u, root: l.r, category: l.c, with: l.with ?? null, outcomes: prior as { [T in Target]: Outcome }, published };
  });
  if (records.length !== raw.meta.utilities) throw new Error(`snapshot lists ${records.length} utilities, its meta says ${raw.meta.utilities}`);
  return { meta: raw.meta, records };
}

export function readSnapshot(): ReturnType<typeof deserialize> {
  return deserialize(readFileSync(SNAPSHOT_PATH, 'utf8'));
}

const STATUSES = ['supported', 'refused', 'invalid', 'mismatch'] as const;
type Counts = { [S in (typeof STATUSES)[number]]: number };
const zero = (): Counts => ({ supported: 0, refused: 0, invalid: 0, mismatch: 0 });

export type Summary = {
  readonly total: number;
  readonly byTarget: { readonly [T in Target]: Counts };
  readonly byCategory: { readonly [C in Category]?: { readonly total: number } & { readonly [T in Target]: Counts } };
  /** Refusals grouped by what blocks them (sweep.ts refusalGroup): utilities per target and utility roots (families) on web, largest first. */
  readonly refusals: readonly { readonly group: string; readonly utilities: { readonly [T in Target]: number }; readonly families: number }[];
  /** Utilities whose published sheet (before the shell pre-pass) compiles for the target. */
  readonly publishedCompiles: { readonly [T in Target]: number };
};

export function summarize(records: readonly UtilityRecord[]): Summary {
  const byTarget = Object.fromEntries(TARGETS.map((t) => [t, zero()])) as { [T in Target]: Counts };
  const byCategory: { [C in Category]?: { total: number } & { [T in Target]: Counts } } = {};
  const groups = new Map<string, { utilities: { [T in Target]: number }; roots: Set<string> }>();
  const publishedCompiles = Object.fromEntries(TARGETS.map((t) => [t, 0])) as { [T in Target]: number };
  for (const r of records) {
    const cat = (byCategory[r.category] ??= { total: 0, web: zero(), ios: zero(), android: zero() });
    cat.total++;
    for (const t of TARGETS) {
      const o = r.outcomes[t];
      byTarget[t][o.status]++;
      cat[t][o.status]++;
      if (o.status === 'refused') {
        let g = groups.get(o.group);
        if (g === undefined) {
          g = { utilities: { web: 0, ios: 0, android: 0 }, roots: new Set() };
          groups.set(o.group, g);
        }
        g.utilities[t]++;
        if (t === 'web') g.roots.add(r.root);
      }
      if (r.published[t].length === 0) publishedCompiles[t]++;
    }
  }
  const refusals = [...groups]
    .map(([group, g]) => ({ group, utilities: g.utilities, families: g.roots.size }))
    .sort((a, b) => b.utilities.web - a.utilities.web || b.utilities.android - a.utilities.android || (a.group < b.group ? -1 : 1));
  return { total: records.length, byTarget, byCategory, refusals, publishedCompiles };
}

export function summaryMarkdown(s: Summary, meta: { readonly chrome: string }): string {
  const pct = (n: number): string => `${((100 * n) / s.total).toFixed(1)}%`;
  const out: string[] = [];
  out.push(`# Tailwind CSS ${TAILWIND_VERSION} sweep`, '');
  out.push(`${s.total} utilities (the package's class list; no variants, no arbitrary values), each compiled by Dragon for web, ios and android and checked in Chrome ${meta.chrome}. Generated by \`pnpm run tw:sweep\`.`, '');
  out.push('| target | supported | refused | invalid | mismatch |', '|---|---:|---:|---:|---:|');
  for (const t of TARGETS) {
    const c = s.byTarget[t];
    out.push(`| ${t} | ${c.supported} (${pct(c.supported)}) | ${c.refused} (${pct(c.refused)}) | ${c.invalid} | ${c.mismatch} |`);
  }
  out.push('', `As published (before the shell pre-pass), the sheet compiles for web ${s.publishedCompiles.web}, ios ${s.publishedCompiles.ios} and android ${s.publishedCompiles.android} of ${s.total} utilities.`, '');
  out.push('## By category (supported / refused / invalid / mismatch)', '', '| category | utilities | web | ios | android |', '|---|---:|---|---|---|');
  for (const c of CATEGORIES) {
    const row = s.byCategory[c];
    if (row === undefined) continue;
    const cell = (x: Counts): string => `${x.supported} / ${x.refused} / ${x.invalid} / ${x.mismatch}`;
    out.push(`| ${c} | ${row.total} | ${cell(row.web)} | ${cell(row.ios)} | ${cell(row.android)} |`);
  }
  out.push('', '## Largest refusal groups (first blocking diagnostic)', '', '| blocked by | web | ios | android | families (web) |', '|---|---:|---:|---:|---:|');
  for (const g of s.refusals.slice(0, 40)) out.push(`| \`${g.group.replace(/\|/g, '\\|')}\` | ${g.utilities.web} | ${g.utilities.ios} | ${g.utilities.android} | ${g.families} |`);
  return `${out.join('\n')}\n`;
}
